import {
  backupChatThread,
  backupProject,
  backupPromptBundle,
  deleteChatBackup,
  deleteProjectBackup,
  deletePromptBackup,
  exportCloudBackups,
  importCloudBackups,
  listChatBackups,
  listProjectBackups,
  listPromptBackups,
  restoreChatBackup,
  restoreCloudStory,
  restoreProjectBackup,
  restorePromptBackup,
} from './cloudBackupService.js';
import {
  getSession,
  isCloudAuthConfigured,
  signInWithGoogle,
  signOut,
  subscribe,
} from './cloudAuthService.js';
import {
  getCloudSyncPreferences,
  runAutoSyncCycle,
  saveCloudSyncPreferences,
  scanCloudSyncState,
  subscribeCloudSyncStatus,
} from './cloudAutoSyncService.js';
import { markProjectBackupDirty } from './projectBackupDirty.js';

export {
  backupChatThread,
  backupProject,
  backupPromptBundle,
  deleteChatBackup,
  deleteProjectBackup,
  deletePromptBackup,
  exportCloudBackups,
  getSession,
  getCloudSyncPreferences,
  importCloudBackups,
  isCloudAuthConfigured,
  listChatBackups,
  listProjectBackups,
  listPromptBackups,
  runAutoSyncCycle,
  restoreChatBackup,
  restoreCloudStory,
  restoreProjectBackup,
  restorePromptBackup,
  saveCloudSyncPreferences,
  scanCloudSyncState,
  signInWithGoogle,
  signOut,
  subscribe,
  subscribeCloudSyncStatus,
  markProjectBackupDirty,
};

export default {
  backupChatThread,
  backupProject,
  backupPromptBundle,
  deleteChatBackup,
  deleteProjectBackup,
  deletePromptBackup,
  exportCloudBackups,
  getSession,
  getCloudSyncPreferences,
  importCloudBackups,
  isCloudAuthConfigured,
  listChatBackups,
  listProjectBackups,
  listPromptBackups,
  runAutoSyncCycle,
  restoreChatBackup,
  restoreCloudStory,
  restoreProjectBackup,
  restorePromptBackup,
  saveCloudSyncPreferences,
  scanCloudSyncState,
  signInWithGoogle,
  signOut,
  subscribe,
  subscribeCloudSyncStatus,
  markProjectBackupDirty,
};
