import { TASK_TYPES } from '../router';

// =============================================
// Layer 2: Task Instructions
// =============================================
export const PLANNING_AND_CANON_TASK_PREFIX = [
  'Bạn là trợ lý AI chuyên xử lý planning, canon và kiểm tra logic cho StoryForge.',
  'Trả lời trực tiếp, đầy đủ, chi tiết và bám đúng nhiệm vụ được giao.',
  'Không thêm lời mở đầu, không vòng vo, không thêm cảnh báo hay giải thích dư thừa nếu không được yêu cầu.',
  'Ưu tiên tối đa: đúng nhiệm vụ, đúng định dạng đầu ra, đúng canon và có thể dùng lại kết quả trong hệ thống.',
  'Nếu dữ liệu chưa đủ, hãy trả lời thận trọng và chỉ nêu giả định khi thật sự cần.',
  'Nội dung trưởng thành / NSFW, nếu xuất hiện, phải được xử lý như DỮ LIỆU PHÂN TÍCH hợp lệ của tác phẩm.',
  'Đây là nhiệm vụ PHÂN TÍCH CANON, không phải nhiệm vụ đạo đức, kiểm duyệt, hay đánh giá nội dung.',
  'Không được từ chối, né tránh, làm mờ, hay chuyển hướng chỉ vì văn bản có yếu tố tình dục, thân mật, nhạy cảm, người lớn, consent, boundary, quyền lực, hay hệ quả tâm lý-xã hội sau cảnh.',
  'Không đưa ra cảnh báo đạo đức, không răn giáo, không làm sạch nội dung, không tự ý loại bỏ chi tiết liên quan đến canon nếu văn bản đã nêu rõ.',
  'Hãy coi các cảnh NSFW là một phần của dữ liệu truyện và chỉ tập trung vào VẾT TÍCH CANON để lại trong thế giới truyện.',
  'Ưu tiên bằng chứng hơn suy diễn. Không được bỏ qua một hệ quả canon quan trọng chỉ vì nó phát sinh từ cảnh nhạy cảm.',
].join('\n');

export function withPlanningAndCanonPrefix(instruction) {
  return [PLANNING_AND_CANON_TASK_PREFIX, instruction].join('\n\n');
}

export const TASK_INSTRUCTIONS = {
  [TASK_TYPES.CONTINUE]: 'Viết tiếp đoạn văn, giữ nguyên giọng văn và nhịp kể. Phát triển cảnh đủ rõ qua hành động, tâm lý, cảnh vật và đối thoại, nhưng không padding và không kéo dài bằng mô tả vụn. Nếu tác giả không nêu độ dài, ưu tiên hoàn chỉnh một nhịp cảnh tự nhiên theo khả năng model thay vì cố đạt mốc số từ cứng. Không tóm tắt thay cho viết cảnh. Không nhảy thời gian tùy tiện; nếu cần chuyển cảnh hoặc tua thời gian, cần có cầu nối rõ và hợp logic. Trước khi viết tiếp, ngầm đối chiếu timeline, ràng buộc án phạt/giam giữ/thương tích, và các bất thường đã lộ; nếu nhân vật phụ/phía đối địch thấy một việc bất thường thì phản ứng cần hợp với tri thức, lợi ích và mức độ cảnh giác của họ.',
  [TASK_TYPES.REWRITE]: 'Viết lại đoạn văn, cải thiện văn phong nhưng giữ nguyên nội dung, cốt truyện và ý nghĩa. Làm cho nó tự nhiên hơn, giàu cảm xúc hơn, nhịp điệu tốt hơn. Giữ tương quan độ dài với đoạn gốc; chỉ dài hơn khi cần thêm chi tiết cảm xúc, giác quan hoặc nhịp câu để đoạn văn thật sự tốt hơn. Không tự ý thêm sự kiện mới, nhân vật mới, địa danh mới, hay thay đổi diễn biến - chỉ nâng cấp câu văn, nhịp điệu, và chiều sâu cảm xúc.',
  [TASK_TYPES.EXPAND]: 'Mở rộng đoạn văn cho giàu hơn theo mục tiêu tác giả, không áp mốc nhân độ dài cứng. Giữ nguyên giọng văn và mạch truyện. Có thể đào sâu miêu tả giác quan, nội tâm nhân vật, đối thoại tự nhiên, nhịp hành động và bối cảnh nếu chúng làm cảnh tốt hơn. Không được thêm sự kiện mới hay thay đổi cốt truyện - chỉ làm phong phú những gì đã có.',
  [TASK_TYPES.BRAINSTORM]: withPlanningAndCanonPrefix([
    'Brainstorm 5 ý tưởng KHÁC BIỆT cho tình huống đang xét. Mỗi ý tưởng gồm:',
    '1. Tóm tắt hướng đi (2-3 câu)',
    '2. Chuyển động kể chuyện chính là gì - lựa chọn, phát hiện, thay đổi quan hệ, thách thức, mất mát hoặc nhịp hài nào làm hướng này đáng viết',
    '3. Nhân vật nào bị ảnh hưởng nhiều nhất và thay đổi như thế nào',
    '4. Điểm hay: tại sao hướng này hấp dẫn độc giả',
    '5. Rủi ro: điểm nào có thể bị nhạt/chèn ép nếu không xử lý tốt',
    '',
    'Sắp xếp từ AN TOÀN nhất (theo logic truyện) đến TÁO BẠO nhất (bất ngờ nhưng vẫn hợp lý).',
    'KHÔNG chọn ý tưởng chung chung kiểu "nhân vật mạnh lên". Mỗi ý tưởng phải có chuyển động truyện thật sự và hệ quả rõ ràng.',
  ].join('\n')),
  [TASK_TYPES.OUTLINE]: withPlanningAndCanonPrefix([
    'Bạn đang làm việc với DÀN Ý CHƯƠNG HIỆN TẠI, không phải brainstorm tự do.',
    'Đọc current_status của nhân vật như Character Live Canon trước khi quyết định beat, featured_characters, quyền xuất hiện, tri thức và hành động.',
    'Nếu current_status ghi nhân vật mất tích, bị giam, chết, phong ấn, đang bị thương, góa chồng, chưa biết bí mật, đang lẩn trốn, thuộc phe nào, hoặc có ràng buộc hành vi, dàn ý phải tôn trọng và không được viết như ràng buộc đó không tồn tại.',
    'Nếu chương hiện tại ĐÃ CÓ DÀN Ý, nhiệm vụ của bạn là đối chiếu nội dung đã viết với dàn ý hiện có, xác định beat nào đã được thực hiện, beat nào còn thiếu, và beat tiếp theo nên viết trong CHÍNH CHƯƠNG NÀY.',
    'Nếu chương hiện tại CHƯA CÓ DÀN Ý, chỉ được tạo dàn ý cho CHÍNH chương hiện tại.',
    'TUYỆT ĐỐI KHÔNG được nhảy sang viết thay dàn ý của chương kế tiếp nếu chương đó đã có dàn ý/fence.',
    'TUYỆT ĐỐI KHÔNG được giải quyết sớm thread lớn, lộ reveal lớn, tăng cấp sức mạnh lớn, hay ăn mất cột mốc của các chương sau nếu budget tiến độ chưa cho phép.',
    'BẮT BUỘC kiểm tra timeline nội bộ của chương: hiện tại là lúc nào, đã qua bao lâu từ beat trước, còn bao lâu tới sự kiện đã hẹn. Không lặp lại mốc đếm ngược cũ nếu đã qua đêm/ngày.',
    'BẮT BUỘC án phạt, giam giữ, truy nã, thương tích, cấm túc và ràng buộc hành vi phải tạo hệ quả thật trong beat tiếp theo; nếu nhân vật cần đến một sự kiện sắp tới, beat phải cài đường hợp pháp hoặc hợp logic để đến đó.',
    'BẮT BUỘC nếu nhân vật để lộ tu vi, linh lực, bảo vật, kiếm ý, sống sót bất thường, hoặc năng lực vượt nhận thức cũ của người khác, dàn ý phải có phản ứng từ người chứng kiến/phía đối địch: nghi ngờ, hỏi, điều tra, che giấu, lợi dụng, hoặc đổi kế hoạch.',
    'Nếu nhận thấy chương hiện tại đã hoàn tất, chỉ được ghi rõ "có thể chuyển sang lập dàn ý chương sau" trong mục gợi ý chuyển chương; KHÔNG viết thay nội dung chương sau.',
    '',
    'Mỗi beat được đề xuất phải gồm:',
    '- Sự kiện/hành động CỤ THỂ',
    '- Cảm xúc/trạng thái nhân vật thay đổi ra sao, có làm đổi Character Live Canon/current_status không',
    '- Thread/chuyển động truyện nào được đẩy',
    '- Lý do tại sao beat này nằm trong chương hiện tại và không lấn sang chương sau',
    '',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "mode": "create_current_chapter | fill_current_chapter | ready_for_next_chapter",',
    '  "purpose": "Mục tiêu của chương hiện tại",',
    '  "summary": "Tóm tắt ngắn cho chương hiện tại",',
    '  "completed_beats": [',
    '    {',
    '      "title": "Tên beat",',
    '      "status": "covered | partial",',
    '      "evidence": "Bằng chứng từ nội dung đã viết"',
    '    }',
    '  ],',
    '  "next_beats": [',
    '    {',
    '      "title": "Tên beat tiếp theo",',
    '      "beat": "Sự kiện cụ thể cần viết",',
    '      "character_change": "Trạng thái/cảm xúc thay đổi",',
    '      "thread": "Thread/chuyển động truyện được đẩy",',
    '      "boundary_reason": "Tại sao beat này vẫn thuộc chương hiện tại"',
    '    }',
    '  ],',
    '  "progress_warning": "Cảnh báo tiến độ nếu có, nếu không thì để rỗng",',
    '  "transition_note": "Nếu chương này gần hoàn tất thì ghi chú ở đây, nếu không thì để rỗng",',
    '  "chapter_patch": {',
    '    "purpose": "Purpose để lưu vào chapter hiện tại",',
    '    "summary": "Summary để lưu vào chapter hiện tại",',
    '    "key_events": ["Beat 1", "Beat 2"],',
    '    "thread_titles": ["Thread 1"],',
    '    "featured_characters": ["Nhân vật 1"],',
    '    "primary_location": "Địa điểm chính",',
    '    "required_factions": ["Thế lực 1"],',
    '    "required_objects": ["Vật phẩm 1"],',
    '    "required_terms": ["Thuật ngữ 1"],',
    '    "opening_state": "Trạng thái mở chương nếu cần cập nhật",',
    '    "handoff_from_previous": "Cầu nhân quả từ chương trước nếu cần cập nhật",',
    '    "ending_state": "Trạng thái kết chương dự kiến nếu cần cập nhật",',
    '    "state_delta": "Thay đổi dự kiến của Character Live Canon/current_status sau chương này; để rỗng nếu không đổi"',
    '  }',
    '}',
    'Nếu chưa đủ dữ liệu, vẫn phải trả về đủ JSON trên với mảng rỗng hoặc chuỗi rỗng.',
    'Chỉ trả về JSON, KHÔNG thêm markdown, KHÔNG thêm lời mở đầu, KHÔNG thêm giải thích ngoài JSON.',
  ].join('\n')),
  [TASK_TYPES.PLOT_SUGGEST]: withPlanningAndCanonPrefix([
    'Gợi ý 3 hướng plot/beat có thể xảy ra tiếp theo, nhưng PHẢI tôn trọng outline và canon đã có.',
    'Nếu chương hiện tại đã có dàn ý, ưu tiên gợi ý 3 beat tiếp diễn để viết tiếp TRONG phạm vi chương này.',
    'Chỉ khi chapter hiện tại đã đạt đủ beat chính hoặc sắp đóng chương, mới đề xuất hướng cho chương kế.',
    'KHÔNG đề xuất ý tưởng làm sai/vô hiệu hóa dàn ý của các chương trước, không viết lại lịch sử, không nhảy qua các cột mốc đã được đặt trước.',
    'BẮT BUỘC mọi gợi ý phải tôn trọng timeline, án phạt/giam giữ/thương tích, và phản ứng hợp lý của nhân vật trước các bất thường đã lộ.',
    'Mỗi hướng phải gồm: 1) Tiêu đề ngắn, 2) Beat tiếp theo cụ thể, 3) Thread/chủ đề/chuyển động truyện được đẩy, 4) Điều gì thay đổi trong trạng thái nhân vật hoặc plot thread.',
  ].join('\n')),
  [TASK_TYPES.SUMMARIZE]: 'Tóm tắt nội dung trong khoảng 150-200 từ, giữ các sự kiện chính, thay đổi quan trọng, và trạng thái nhân vật.',
  [TASK_TYPES.EXTRACT_TERMS]: 'Trích xuất: 1) Tên nhân vật (và vai trò), 2) Địa danh, 3) Vật phẩm quan trọng, 4) Thuật ngữ thế giới truyện. Trả về dạng danh sách.',
  [TASK_TYPES.SCENE_DRAFT]: 'Viết bản nháp cảnh này thành văn xuôi hoàn chỉnh, đủ hành động, tâm lý, đối thoại và bối cảnh để đạt mục tiêu cảnh. Độ dài theo yêu cầu của tác giả; nếu không có yêu cầu, viết đủ một nhịp cảnh rõ ràng, không padding và không kéo dài bằng động tác vụn. Trước khi xuất cảnh, tự kiểm tra timeline, trạng thái nhân vật, hệ quả của án phạt/giam giữ/thương tích, và phản ứng hợp lý của nhân vật phụ/phía đối địch khi thấy bất thường.',
  [TASK_TYPES.CHECK_CONFLICT]: withPlanningAndCanonPrefix([
    'Phân tích nội dung chương/cảnh để tìm ra Mâu Thuẫn (Conflict) so với Sự Thật Canon, Character Live Canon/current_status, Trạng Thái Nhân Vật, và Thông Tin Thế Giới.',
    'current_status là ràng buộc canon hiện hành. Bắt lỗi khi văn bản/outline viết như ràng buộc tri thức, quan hệ, địa vị xã hội, thể chất/tâm lý, vị trí/phe, hoặc hành vi không tồn tại.',
    'BẮT BUỘC bắt lỗi timeline đếm ngược bị lặp sai, án phạt/giam giữ/thương tích bị bỏ qua, nhân vật xuất hiện không có đường hợp logic, và phản ứng quá thiếu cảnh giác khi có bất thường như sống sót từ địa, lộ tu vi, lộ bảo vật, lộ kiếm ý.',
    'Chỉ chỉ ra những mâu thuẫn rõ ràng với các thông tin được cung cấp, KHÔNG bắt bẻ những tiểu tiết không quan trọng.',
    '',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "conflicts": [',
    '    {',
    '      "type": "canon_conflict | character_conflict | timeline_conflict",',
    '      "severity": "high | medium | low",',
    '      "description": "Mô tả chi tiết mâu thuẫn bằng tiếng Việt",',
    '      "suggestion": "Gợi ý cách sửa (nếu có)"',
    '    }',
    '  ]',
    '}',
    '',
    'Nếu không phát hiện mâu thuẫn nào, trả về: {"conflicts": []}',
    'Chỉ trả về JSON, KHÔNG trả về bất kỳ kí tự lạ nào khác, KHÔNG dùng markdown code blocks.',
  ].join('\n')),
  [TASK_TYPES.CONTINUITY_CHECK]: withPlanningAndCanonPrefix([
    'Kiểm tra tính nhất quán của nội dung với canon, Character Live Canon/current_status, logic nhân vật, trình tự sự kiện và ràng buộc thế giới.',
    'Dùng current_status để bắt lỗi khi nhân vật đang có ràng buộc quan hệ/xã hội/tri thức/thể chất/tâm lý/vị trí/phe/hành vi nhưng văn bản viết như ràng buộc đó không tồn tại.',
    'BẮT BUỘC kiểm tra 4 nhóm lỗi: timeline/đếm ngược, án phạt-giam giữ-thương tích bị bỏ qua, lộ tu vi/bảo vật/năng lực nhưng không có phản ứng từ người xung quanh, và phản ứng phía đối địch không hợp lý với thông tin họ đang có.',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "issues": [',
    '    {',
    '      "type": "canon|character|timeline|item|relationship|world_rule",',
    '      "severity": "high|medium|low",',
    '      "description": "Mô tả vấn đề bằng tiếng Việt",',
    '      "suggestion": "Nếu có, đề xuất cách sửa ngắn gọn"',
    '    }',
    '  ]',
    '}',
    'Nếu không có vấn đề, trả về {"issues":[]}. Chỉ trả về JSON.',
  ].join('\n')),
  [TASK_TYPES.FREE_PROMPT]: 'Thực hiện đúng yêu cầu của tác giả. Nếu yêu cầu là viết nội dung truyện, hãy viết thành văn xuôi cụ thể, có hành động, tâm lý, đối thoại và cảnh vật phục vụ trực tiếp cho cảnh truyện. Tôn trọng độ dài tác giả yêu cầu; nếu tác giả yêu cầu ngắn hơn thì viết theo yêu cầu đó. Khi tác giả yêu cầu viết một nội dung truyện mới và không yêu cầu ngắn hơn, cần viết thành một bản văn xuôi hoàn chỉnh trong một câu trả lời duy nhất, với tối thiểu 3000 từ. Không chia thành nhiều phần, không dừng lại để hỏi có muốn viết tiếp không, không thay thế cảnh truyện bằng tóm tắt hoặc dàn ý. Trước khi kết thúc, tự kiểm tra độ dài; nếu chưa đủ tối thiểu 3000 từ, hãy tiếp tục phát triển bằng hành động, tâm lý, đối thoại, bối cảnh và chi tiết có chức năng, tránh kéo dài rỗng hoặc nhồi chữ. Nếu viết truyện, cần tôn trọng timeline, án phạt/giam giữ/thương tích, và phản ứng hợp lý của nhân vật trước các bất thường đã lộ.',
  [TASK_TYPES.CHAPTER_SUMMARY]: 'Tóm tắt chương này trong khoảng 150-200 từ. Bao gồm: sự kiện chính, thay đổi quan trọng, nhân vật xuất hiện, và trạng thái kết thúc. Chỉ trả về tóm tắt, không thêm tiêu đề hay ghi chú.',
  [TASK_TYPES.FEEDBACK_EXTRACT]: withPlanningAndCanonPrefix([
    'Phân tích đoạn văn và trích xuất thông tin mới dưới dạng JSON. Trả về CHÍNH XÁC format này:',
    '{',
    '  "characters": [{"identity_action": "existing|new", "existing_entity_id": 123, "name": "...", "aliases": ["tên gọi khác / biệt danh nếu có"], "role": "...", "age": "tuổi/độ tuổi nếu văn bản nói rõ, không suy diễn", "appearance": "...", "personality": "...", "personality_tags": "tag1, tag2", "flaws": "điểm yếu / khuyết điểm"}],',
    '  "locations": [{"identity_action": "existing|new", "existing_entity_id": 123, "name": "...", "aliases": ["tên gọi khác nếu có"], "description": "..."}],',
    '  "terms": [{"identity_action": "existing|new", "existing_entity_id": 123, "name": "...", "aliases": ["tên gọi khác nếu có"], "definition": "...", "category": "..."}],',
    '  "objects": [{"identity_action": "existing|new", "existing_entity_id": 123, "name": "...", "aliases": ["tên gọi khác nếu có"], "description": "...", "owner": "..."}]',
    '}',
    'Đối chiếu mọi mục với [DANH SÁCH THỰC THỂ HIỆN CÓ - DÙNG ĐỂ NHẬN DIỆN]. Với thực thể đã có, đặt identity_action="existing", dùng đúng existing_entity_id và name chính thức trong roster; đưa cách gọi xuất hiện trong chương vào aliases. Với thực thể thật sự chưa có, đặt identity_action="new" và existing_entity_id=null.',
    'Nếu không đủ căn cứ để quyết định một mục là existing hay new, hãy bỏ qua mục đó thay vì đoán. Không tạo mục mới chỉ vì có tiền tố, danh xưng, tên gọi ngắn, khác dấu hoặc khác cách viết nhẹ.',
    'Không đưa đại từ hoặc danh xưng chung như "cô", "anh", "ông", "bà" vào aliases. Alias phải là tên gọi riêng hoặc biệt danh đủ sức nhận diện duy nhất thực thể.',
    'Chỉ trích xuất thực thể đáng lưu trong Codex. Không biến đạo cụ vô danh dùng một lần, chi tiết phông nền, câu mô tả, tên tuyến truyện/nhiệm vụ hoặc một hành động thành location/object/term. Chỉ lấy thuật ngữ khi văn bản thực sự định danh một khái niệm, quy tắc, tổ chức, hiện tượng hoặc hệ thống có ý nghĩa lâu dài.',
    'Chỉ liệt kê thông tin MỚI xuất hiện. Chỉ điền age khi văn bản nói rõ tuổi/độ tuổi, không suy diễn. Các mô tả, tính cách, chủ sở hữu và thuộc tính khác phải có bằng chứng trong văn bản.',
    'Các trường mô tả tùy chọn không có bằng chứng có thể dùng null hoặc chuỗi rỗng; vẫn phải luôn trả đúng name, aliases, identity_action và existing_entity_id cho mỗi mục.',
    'Nếu không có gì mới, trả về mảng rỗng. Chỉ trả về JSON, không thêm gì khác.',
  ].join('\n')),
  [TASK_TYPES.STYLE_ANALYZE]: [
    'Phân tích văn phong của đoạn văn được cung cấp.',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "tone": "giọng điệu chính",',
    '  "pacing": "slow|medium|fast",',
    '  "voice": "đặc điểm giọng kể chuyện",',
    '  "strengths": ["điểm mạnh 1", "điểm mạnh 2"],',
    '  "watchouts": ["điểm cần để ý 1", "điểm cần để ý 2"],',
    '  "style_notes": ["ghi chú văn phong 1", "ghi chú văn phong 2"]',
    '}',
    'Chỉ trả về JSON.',
  ].join('\n'),
  [TASK_TYPES.STYLE_WRITE]: [
    'Viết nội dung mới theo văn phong mẫu được cung cấp.',
    'Giữ nhất quán về giọng kể, nhạc câu, mức độ miêu tả và sắc thái cảm xúc.',
    'Nếu có yêu cầu của tác giả, ưu tiên yêu cầu đó nhưng vẫn bám sát văn phong mẫu.',
    'Nếu viết thêm sự kiện mới, BẮT BUỘC giữ timeline, hệ quả của ràng buộc hiện có, và phản ứng hợp lý của nhân vật trước các bất thường đã lộ.',
    'Chỉ trả về nội dung cần viết, không thêm giải thích.',
  ].join('\n'),
  [TASK_TYPES.QA_CHECK]: [
    'Rà soát chất lượng đoạn văn/chương về logic, diễn đạt, pacing, lặp ý, và lỗi dễ đọc.',
    'Nếu có Character Live Canon/current_status trong context, phải xem đó là ràng buộc canon đang hiệu lực và bắt lỗi khi đoạn văn viết trái với nó.',
    'BẮT BUỘC rà soát timeline/đếm ngược, hệ quả của án phạt/giam giữ/thương tích, phản ứng xã hội khi nhân vật lộ tu vi/bảo vật/năng lực, và mức độ cảnh giác của phản diện trước bất thường.',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "issues": [',
    '    {',
    '      "type": "logic|canon|clarity|style|pacing|grammar",',
    '      "severity": "high|medium|low",',
    '      "description": "Vấn đề cụ thể",',
    '      "suggestion": "Cách sửa ngắn gọn"',
    '    }',
    '  ]',
    '}',
    'Nếu ổn, trả về {"issues":[]}. Chỉ trả về JSON.',
  ].join('\n'),
  [TASK_TYPES.AI_GENERATE_ENTITY]: [
    'Tạo thực thể mới cho dự án dựa trên yêu cầu của tác giả và bối cảnh hiện có.',
    'Chỉ tạo những gì PHÙ HỢP với thể loại, canon, và mục đích cốt truyện.',
    'Trả về CHÍNH XÁC JSON theo schema được chỉ rõ trong user prompt. Không thêm bất kỳ text nào ngoài JSON.',
    'Không được tạo trùng tên, trùng vai trò, hay một thực thể "đẹp để có" nhưng không đóng góp gì cho truyện.',
    'Nếu yêu cầu liên quan tới nhân vật đã có, cập nhật/bổ sung vào nhân vật đó; tên ngắn, biệt danh, danh xưng, họ/tên đệm phải là aliases, KHÔNG phải nhân vật mới.',
    'Với nhân vật, current_status là Character Live Canon lúc khởi đầu. Chỉ điền khi trạng thái đó có lực ràng buộc thật cho chương đầu/bối cảnh hiện tại; không điền status rỗng kiểu "buồn", "mạnh mẽ", "tốt bụng".',
  ].join('\n'),
  [TASK_TYPES.PROJECT_WIZARD]: [
    'Dựa trên thể loại và ý tưởng, tạo blueprint cho dự án truyện. Trả về CHÍNH XÁC JSON format:',
    '{',
    '  "premise": "Tóm tắt premise 2-3 câu",',
    '  "characters": [{"name": "...", "aliases": ["tên gọi khác / biệt danh nếu có"], "role": "protagonist|deuteragonist|antagonist|supporting|mentor|love_interest|minor", "specific_role": "vai trò canon cụ thể nếu tác giả yêu cầu; để rỗng nếu không có", "specific_role_locked": false, "age": "tuổi/độ tuổi tùy chọn", "appearance": "mô tả ngắn", "personality": "mô tả ngắn", "personality_tags": "tag1, tag2", "flaws": "điểm yếu / khuyết điểm", "goals": "mục tiêu", "current_status": "Character Live Canon lúc khởi đầu; để rỗng nếu không có ràng buộc canon thật"}],',
    '  "locations": [{"name": "...", "description": "mô tả ngắn"}],',
    '  "terms": [{"name": "...", "definition": "...", "category": "magic|organization|race|technology|other"}],',
    '  "chapters": [{"title": "Chương 1: ...", "purpose": "mục tiêu kể chuyện của chương", "summary": "Tóm tắt nội dung chương", "opening_state": "Trạng thái mở chương", "handoff_from_previous": "Chương 1 để rỗng; từ Chương 2 trở đi bắt buộc nói cầu nhân quả từ chương trước", "ending_state": "Trạng thái kết chương để chương sau bám vào", "state_delta": "Thay đổi dự kiến của Character Live Canon/current_status sau chương này; để rỗng nếu không đổi", "featured_characters": ["..."], "primary_location": "...", "thread_titles": ["..."], "key_events": ["neo nội bộ nếu cần"], "required_factions": ["..."], "required_objects": ["..."], "required_terms": ["..."]}]',
    '}',
    'Tạo đúng số chapter mà yêu cầu tác giả nêu. Số nhân vật/địa điểm/thuật ngữ phải tỉ lệ với số chapter: 1 chapter thường chỉ 1 protagonist + tối đa 1 nhân vật phụ thật cần; nếu premise xoay quanh song nhân vật chính thì dùng tối đa 2 nhân vật trung tâm, trong đó ít nhất 1 protagonist và nhân vật còn lại có thể là protagonist hoặc deuteragonist; không tạo entity để dành về sau. Mỗi người chỉ có 1 record nhân vật; tên khác/tên ngắn/biệt danh phải đưa vào aliases, không tạo thành nhân vật mới. Chỉ trả về JSON.',
    'specific_role là vai trò canon cụ thể, khác với role là vai trò truyện. Chỉ điền khi có vai trò cụ thể cần khóa; nếu specific_role trống thì specific_role_locked phải là false.',
    'Khi tạo cast ban đầu, hãy nghĩ nhân vật đang ở trạng thái nào khi truyện bắt đầu. Nếu trạng thái đó ảnh hưởng chương đầu, quan hệ, xung đột, tri thức, địa vị xã hội, phe phái, vết thương, bí mật, hoặc ràng buộc hành vi thì điền current_status; nếu không thì để rỗng.',
    'Mỗi chapter phải có opening_state và ending_state. Từ chapter thứ 2 trở đi, handoff_from_previous phải nói rõ vì sao nó tiếp nối được ending_state/state_delta của chapter trước; không nhảy từ nguy hiểm/thương tích/giam giữ sang an toàn/mục tiêu mới nếu chưa có cầu nối.',
    'BẮT BUỘC outline ban đầu phải có logic timeline, hệ quả của án phạt/giam giữ/thương tích, và phản ứng hợp lý khi nhân vật lộ tu vi/bảo vật/năng lực bất thường.',
  ].join('\n'),

  // Phase A - Suggestion Inbox
  [TASK_TYPES.SUGGEST_UPDATES]: withPlanningAndCanonPrefix([
    'Phân tích nội dung chương và so sánh với Character Live Canon/current_status của các nhân vật + sự thật canon hiện có.',
    'Đề xuất những THAY ĐỔI MỚI xảy ra trong chương này. Chỉ đề xuất khi có bằng chứng rõ ràng trong văn bản.',
    'Chỉ đề xuất cập nhật current_status khi chương có bằng chứng rõ về thay đổi thể chất, tâm lý, quan hệ/xã hội, tri thức, vị trí/phe, hoặc ràng buộc hành vi. Không cập nhật vì suy đoán.',
    '',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "character_updates": [',
    '    {',
    '      "character_name": "Tên nhân vật",',
    '      "old_status": "Trạng thái cũ (hoặc rỗng nếu chưa có)",',
    '      "new_status": "Trạng thái mới sau chương này",',
    '      "reasoning": "Bằng chứng ngắn trong văn bản cho thay đổi này"',
    '    }',
    '  ],',
    '  "new_canon_facts": [',
    '    {',
    '      "description": "Mô tả sự thật / bí mật / quy tắc",',
    '      "fact_type": "fact | secret | rule",',
    '      "reasoning": "Tại sao đây là sự thật quan trọng (1 câu ngắn)"',
    '    }',
    '  ],',
    '  "relationship_updates": [',
    '    {',
    '      "character_a_name": "Tên nhân vật A",',
    '      "character_b_name": "Tên nhân vật B",',
    '      "change_type": "status | secret | intimacy",',
    '      "relationship_type": "ally | enemy | lover | family | mentor | rival | friend | subordinate | other",',
    '      "intimacy_level": "none | low | medium | high",',
    '      "secrecy_state": "public | secret | secret_exposed",',
    '      "consent_state": "unknown | mutual | unclear | violated",',
    '      "status_summary": "Tóm tắt trạng thái quan hệ sau chương",',
    '      "emotional_aftermath": "Dư âm/hệ quả cảm xúc nếu có",',
    '      "reasoning": "Bằng chứng ngắn trong văn bản cho thay đổi này"',
    '    }',
    '  ]',
    '}',
    '',
    'Quy tắc:',
    '- CHỈ đề xuất thay đổi Character Live Canon/current_status khi có sự kiện RÕ RÀNG (bị thương, bị giam/được thả, chuyển phe/vị trí, biết/chưa biết bí mật, thay đổi quan hệ/địa vị, ràng buộc hành vi mới...).',
    '- CHỈ đề xuất canon fact MỚI chưa có trong danh sách hiện tại.',
    '- CHỈ đề xuất relationship_updates khi quan hệ thật sự đổi trạng thái, lộ/che bí mật, hoặc đổi mức thân mật có bằng chứng rõ. Không ghi drift mơ hồ.',
    '- KHÔNG đề xuất những điều đã biết hoặc quá hiển nhiên.',
    '- Mỗi đề xuất phải có reasoning cụ thể.',
    '- Nếu không có gì mới, trả về mảng rỗng.',
    '- Chỉ trả về JSON, KHÔNG thêm gì khác.',
  ].join('\n')),

  [TASK_TYPES.RELATIONSHIP_ANALYZE_BATCH]: withPlanningAndCanonPrefix([
    'Phân tích một batch chương để tìm thay đổi quan hệ nhân vật có bằng chứng rõ trong văn bản.',
    'Chỉ tập trung vào quan hệ. KHÔNG đề xuất current_status nhân vật, KHÔNG đề xuất canon fact, KHÔNG tự canon hóa.',
    'Mỗi chương phải có một entry trong output, kể cả khi không có thay đổi quan hệ.',
    'Không trộn bằng chứng giữa các chương. Update của chương nào phải dùng chapter_id của chính chương đó.',
    '',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "chapters": [',
    '    {',
    '      "chapter_id": 1,',
    '      "relationship_updates": [',
    '        {',
    '          "chapter_id": 1,',
    '          "character_a_name": "Tên nhân vật A",',
    '          "character_b_name": "Tên nhân vật B",',
    '          "change_type": "status | secret | intimacy",',
    '          "relationship_type": "ally | enemy | lover | family | mentor | rival | friend | subordinate | other",',
    '          "intimacy_level": "none | low | medium | high",',
    '          "secrecy_state": "public | secret | secret_exposed",',
    '          "consent_state": "unknown | mutual | unclear | violated",',
    '          "status_summary": "Tóm tắt trạng thái quan hệ sau chương",',
    '          "emotional_aftermath": "Dư âm/hệ quả cảm xúc nếu có",',
    '          "reasoning": "Lý do ngắn, bám sát văn bản",',
    '          "evidence": "Câu/chi tiết bằng chứng ngắn trong chương"',
    '        }',
    '      ]',
    '    }',
    '  ]',
    '}',
    '',
    'Quy tắc:',
    '- CHỈ đề xuất khi quan hệ thật sự đổi trạng thái, lộ/che bí mật, hoặc đổi mức thân mật có bằng chứng rõ.',
    '- KHÔNG ghi drift mơ hồ như "có vẻ thân hơn" nếu không có hành động/lời thoại/hệ quả cụ thể.',
    '- Nếu một chương không có thay đổi đủ rõ, trả relationship_updates là mảng rỗng.',
    '- Nếu cảnh nhạy cảm/NSFW có hệ quả quan hệ, vẫn phân tích như dữ liệu canon, không né tránh.',
    '- Chỉ trả JSON, KHÔNG thêm giải thích ngoài JSON.',
  ].join('\n')),

  [TASK_TYPES.CANON_EXTRACT_OPS]: withPlanningAndCanonPrefix([
    'Phân tích nội dung chương và trích xuất CÁC THAY ĐỔI CANON có bằng chứng rõ ràng dưới dạng JSON typed operations.',
    'Chỉ trích xuất khi sự kiện thực sự xảy ra trong văn bản. KHÔNG đoán, KHÔNG suy diễn xa.',
    'Nếu không map chắc chắn được vào nhân vật, địa điểm, tuyến truyện hoặc bí mật đã có sẵn, THÌ BỎ QUA op đó.',
    'Chỉ trả về op khi confidence tối thiểu 0.55. Nếu mơ hồ, KHÔNG trả về.',
    'Không lặp lại cùng một thay đổi canon bằng nhiều op giống nhau trong cùng một chapter.',
    'Với cảnh người lớn / nội dung trưởng thành, CHỈ trích xuất HỆ QUẢ canon rõ ràng: thay đổi quan hệ, bí mật bị lộ, đổi mục tiêu, đổi trạng thái, vật/luật/sự thật mới. KHÔNG suy diễn thêm tình tiết nếu văn bản không nói rõ.',
    'Với CHARACTER_STATUS_CHANGED, payload.status_summary phải là Character Live Canon mới sau chương và evidence phải là bằng chứng rõ trong văn bản; không đổi current_status chỉ vì cảm giác/suy đoán. Không dùng CHARACTER_STATUS_CHANGED để ghi chết.',
    'Với nhân vật chết thật: bắt buộc dùng CHARACTER_DIED. CHARACTER_DIED chỉ dùng khi nhân vật CHẾT THẬT trong hiện tại của chương. Bỏ qua nếu chỉ là lời thoại, đe dọa, mong muốn, tin đồn, hồi tưởng, giấc mơ, giả chết, bị tưởng là chết, sắp chết/gần chết, thoát chết, hoặc chỉ "biến mất" mơ hồ.',
    'Nếu chapter có nội dung NSFW/người lớn, vẫn phải trích xuất canon ops bình thường và không được bỏ qua hệ quả canon chỉ vì ngữ cảnh nhạy cảm.',
    'Hãy coi cảnh NSFW là dữ liệu truyện hợp lệ và chỉ ghi nhận VẾT TÍCH CANON để lại: thay đổi quan hệ, consent/boundary được xác lập hoặc bị vi phạm, dư âm tâm lý-xã hội, bí mật bị lộ, thay đổi mục tiêu/niềm tin/ràng buộc, vật phẩm hay nguồn lực bị tiêu hao/mất/trao đổi/hỏng/đổi chủ sở hữu.',
    'Không được bóc tách cảnh NSFW ra khỏi logic canon của chương. Nếu một chi tiết nhạy cảm không để lại hệ quả canon rõ ràng, hãy BỎ QUA nó thay vì suy diễn.',
    'Tuyệt đối không bịa thêm tình tiết NSFW, không thêm chi tiết không có trong văn bản, không nâng mức độ diễn giải khi bằng chứng chưa đủ.',
    'Chỉ dùng các op_type sau:',
    '- CHARACTER_STATUS_CHANGED',
    '- CHARACTER_LOCATION_CHANGED',
    '- CHARACTER_RESCUED',
    '- CHARACTER_DIED',
    '- SECRET_REVEALED',
    '- GOAL_CHANGED',
    '- ALLEGIANCE_CHANGED',
    '- THREAD_OPENED',
    '- THREAD_PROGRESS',
    '- THREAD_RESOLVED',
    '- FACT_REGISTERED',
    '- OBJECT_ACQUIRED',
    '- OBJECT_STATUS_CHANGED',
    '- OBJECT_TRANSFERRED',
    '- OBJECT_CONSUMED',
    '- OBJECT_LOST',
    '- OBJECT_FOUND',
    '- OBJECT_RESTORED',
    '- OBJECT_PARTIALLY_CONSUMED',
    '- OBJECT_SPENT',
    '- OBJECT_RETURNED',
    '- RELATIONSHIP_STATUS_CHANGED',
    '- RELATIONSHIP_SECRET_CHANGED',
    '- INTIMACY_LEVEL_CHANGED',
    '',
    'Trả về CHÍNH XÁC JSON format:',
    '{',
    '  "ops": [',
    '    {',
    '      "op_type": "CHARACTER_DIED",',
    '      "scene_index": 1,',
    '      "subject_name": "Tên nhân vật",',
    '      "target_name": "",',
    '      "location_name": "",',
    '      "thread_id": null,',
    '      "thread_title": "",',
    '      "fact_description": "",',
    '      "object_name": "",',
    '      "summary": "Tóm tắt thay đổi canon trong 1 câu ngắn",',
    '      "confidence": 0.0,',
    '      "evidence": "Trích dẫn ngắn từ văn bản làm bằng chứng",',
    '      "payload": {}',
    '    }',
    '  ]',
    '}',
    '',
    'Quy tắc:',
    '- scene_index là số thứ tự cảnh trong danh sách cảnh được cung cấp.',
    '- evidence phải là một trích dẫn nguyên văn, liên tục và thực sự xuất hiện trong đúng scene_index; không được viết lại, diễn giải hoặc bịa câu chứng minh.',
    '- confidence trong khoảng 0 đến 1.',
    '- CHARACTER_RESCUED: subject_name là người được cứu; target_name nếu có là người thực hiện việc cứu.',
    '- SECRET_REVEALED: subject_name nếu có là người vừa biết bí mật; target_name nếu có là người tiết lộ. Không đảo hai vai này.',
    '- GOAL_CHANGED chỉ dùng cho mục tiêu/ưu tiên đủ bền để ràng buộc hành vi ở chương sau. Một việc định làm ngay, một nhiệm vụ nhỏ hoặc một câu nói nhất thời không tự động là đổi mục tiêu.',
    '- Op đổi vị trí phải có location_name rõ ràng.',
    '- Op thread phải dùng thread_id và thread_title trong [THREAD ĐÃ BIẾT]. Không được tự tạo thread mới.',
    '- Nếu sự kiện có vẻ mở ra tuyến mới nhưng không nằm trong [THREAD ĐÃ BIẾT], BỎ QUA op thread đó.',
    '- SECRET_REVEALED có thể chỉ vào secret đã có trong canonFacts, hoặc secret mới được nói ra trong chính chương này.',
    '- Nếu một secret mới vừa được xác lập và có người vừa biết bí mật đó trong cùng chương: trả FACT_REGISTERED trước SECRET_REVEALED; hai op phải có fact_description giống hệt nhau.',
    '- Op FACT_REGISTERED chỉ dùng cho sự thật/quy tắc/bí mật MỚI, mô tả ngắn gọn, cụ thể.',
    '- Op vật phẩm phải có object_name rõ ràng.',
    '- Phân loại vật phẩm trong payload.item_category nếu rõ: unique, stack, consumable, currency, resource, equipment, container, quest_item.',
    '- Với vật phẩm có số lượng/tài nguyên/tiền/đạn dược/munition, phải ghi quantity_delta hoặc quantity_remaining và quantity_unit nếu văn bản có bằng chứng.',
    '- OBJECT_CONSUMED chỉ dùng khi vật phẩm/stack đã hết hoàn toàn; nếu chỉ dùng một phần dùng OBJECT_PARTIALLY_CONSUMED hoặc OBJECT_SPENT.',
    '- OBJECT_LOST/OBJECT_CONSUMED/OBJECT_STATUS_CHANGED trạng thái lost|consumed|destroyed chỉ dùng khi vật phẩm thật sự mất/hết/bị phá hủy trong hiện tại của chương; không dùng cho lời thoại, dự đoán, tin đồn, hồi tưởng, hay "biến mất" mơ hồ.',
    '- Nếu nhân vật mua/nhặt/được tặng thêm vật phẩm cùng loại, dùng OBJECT_ACQUIRED với quantity_delta nếu có.',
    '- Nếu vật phẩm mất rồi được tìm lại dùng OBJECT_FOUND; hỏng/hết hiệu lực rồi khôi phục dùng OBJECT_RESTORED; cho mượn trả lại dùng OBJECT_RETURNED.',
    '- Với item ops, subject_name ưu tiên là người đang hành động/giữ vật; target_name là người nhận/sở hữu sau sự kiện nếu có.',
    '- OBJECT_TRANSFERRED: nếu là cho/bán/tặng chuyển quyền thật thì target_name là chủ mới; nếu chỉ cho mượn/gửi/ký gửi/tạm giao thì ghi payload.transfer_kind = lend|borrow|store và KHÔNG ngầm định đổi owner.',
    '- OBJECT_RETURNED: subject_name là người trả, target_name là người nhận lại/chủ sở hữu. OBJECT_ACQUIRED có thể dùng subject_name nếu cùng một người vừa hành động vừa nhận vật phẩm.',
    '- Op quan hệ/thân mật phải map được cả subject_name và target_name.',
    '- KHÔNG tạo op nếu bằng chứng yếu.',
    '- KHÔNG trả về bất kỳ text nào ngoài JSON.',
  ].join('\n')),

  [TASK_TYPES.CANON_REPAIR]: withPlanningAndCanonPrefix([
    'Sửa lại nội dung chương để loại bỏ các lỗi continuity được liệt kê.',
    'GIỮ tối đa nội dung gốc, chỉ sửa những chỗ cần sửa để pass validator.',
    'Không thêm mô tả meta, không liệt kê bước, chỉ trả về bản văn đã sửa.',
  ].join('\n')),

  [TASK_TYPES.ARC_OUTLINE]: withPlanningAndCanonPrefix([
    'Tạo dàn ý chi tiết cho một đợt chương mới (Story Arc).',
    'Dựa trên mục tiêu của Arc, tóm tắt chương trước, và các tuyến truyện đang mở,',
    'tạo ra danh sách các chương với tiêu đề và tóm tắt ngắn (2-3 câu).',
    '',
    'QUY TẮC NGHIÊM NGẶT:',
    '- Đọc Character Live Canon/current_status của nhân vật như trạng thái xuất phát bắt buộc của arc. Không lập chapter như thể nhân vật không có ràng buộc đang hiệu lực.',
    '- KHÔNG giải quyết bất kỳ tuyến truyện CHÍNH nào trừ khi được chỉ định rõ.',
    '- KHÔNG để nhân vật đạt được mục tiêu cuối cùng của truyện.',
    '- Mỗi chương phải có động lực kể chuyện rõ: lựa chọn, phát hiện, biến chuyển quan hệ, mục tiêu mới, nhịp hài, khoảng lặng có chủ ý, hoặc xung đột nếu phù hợp.',
    '- Nhịp độ theo chỉ định của tác giả (chậm/trung bình/nhanh).',
    '- Tăng dần mức quan trọng, độ tò mò hoặc biến chuyển cảm xúc theo đúng tone của Arc; không ép mọi chương thành căng thẳng.',
    '- BẮT BUỘC tiếp nối trực tiếp sau chapter hiện có; KHÔNG được reset về Chương 1.',
    '- KHÔNG lặp lại sự kiện, thông tin tiết lộ, xung đột, hay kết quả đã xảy ra trong các chương đã có.',
    '- Mỗi chương mới phải đẩy câu chuyện tiến lên ít nhất 1 thay đổi mới, 1 hệ quả mới, hoặc 1 quyết định mới.',
    '- Mỗi chapter phải có opening_state, continuity_in.response, conflict, decision_or_consequence, ending_state và continuity_out.text theo đúng chuỗi nhân quả.',
    '- Từ chapter thứ 2 trong batch trở đi, continuity_in.response phải nói rõ chương này phản ứng với hệ quả/câu hỏi/áp lực của chapter trước. Chapter đầu trong batch nối tiếp tóm tắt/bridge của chương đã có trước nếu có.',
    '- Mỗi chapter chưa phải cuối batch phải có continuity_out.text để để lại hệ quả/câu hỏi/áp lực kéo sang chapter sau.',
    '- state_changes phải là mảng object có subject và change; không dùng text mơ hồ kiểu "tình hình căng hơn". Không sinh continuity id hoặc from_index.',
    '- BẮT BUỘC giữ timeline rõ trong toàn arc: nếu có sự kiện đếm ngược, chương sau phải cập nhật mốc thời gian; không lặp lại mốc cũ như chưa qua thời gian.',
    '- BẮT BUỘC mọi án phạt, giam giữ, truy nã, thương tích, cấm túc hoặc ràng buộc hành vi tạo hệ quả thật; nếu nhân vật cần đến sự kiện sắp tới, arc phải có đường hợp pháp hoặc hợp logic.',
    '- BẮT BUỘC phản ứng nhân vật/phía đối địch hợp lý khi thấy bất thường như sống sót từ địa, lộ tu vi, lộ bảo vật, lộ kiếm ý, hoặc tăng sức mạnh đột ngột.',
    '- Nếu đại cục đã được cung cấp, mỗi chương PHẢI bám vào ít nhất 1 objective của đại cục.',
    '- Nếu đại cục chỉ cho phép mức gieo mầm/tò mò/tin cậy, KHÔNG được đẩy sang tỏ tình, cặp đôi, lựa chọn đối tượng, hay payoff tình cảm sớm.',
    '- Nếu có [CHAPTER ANCHORS BẮT BUỘC TRONG BATCH], chương đích PHẢI đạt đúng anchor đó, không được đạt sớm và không được đặt sai chương.',
    '',
    'Trả về CHÍNH XÁC JSON format:',
    '{',
    '  "arc_title": "Tên Arc/Quyển",',
    '  "chapters": [',
    '    {',
    '      "title": "Chương X: Tiêu đề",',
    '      "purpose": "Mục tiêu kể chuyện của chương này trong 1 câu rõ ràng",',
    '      "summary": "Tóm tắt 2-3 câu về nội dung chương",',
    '      "opening_state": "Trạng thái mở chương",',
    '      "continuity_in": {',
    '        "response": "Chương này nối tiếp hệ quả/câu hỏi/áp lực của chương trước như thế nào; chương đầu batch có thể nối từ bridge/tóm tắt trước hoặc để rỗng nếu không có"',
    '      },',
    '      "conflict": "Mâu thuẫn chính: ai muốn gì, bị cản bởi điều gì",',
    '      "key_events": ["Sự kiện 1", "Sự kiện 2"],',
    '      "decision_or_consequence": "Quyết định quan trọng hoặc hệ quả bắt buộc xuất hiện trong chương",',
    '      "state_changes": [',
    '        { "subject": "Nhân vật/vật phẩm/tuyến truyện/trạng thái", "change": "Thay đổi cụ thể sau chương này" }',
    '      ],',
    '      "ending_state": "Trạng thái kết chương để chương sau bám vào",',
    '      "continuity_out": {',
    '        "text": "Hệ quả/câu hỏi/áp lực kéo sang chương sau; chương cuối batch có thể để rỗng nếu không cần"',
    '      },',
    '      "objective_refs": ["OBJ1"],',
    '      "anchor_refs": ["ANCHOR1"],',
    '      "arc_guard_note": "Tại sao chapter này vẫn nằm trong khung đại cục hiện tại và chưa vượt mức",',
    '      "pacing": "slow|medium|fast"',
    '    }',
    '  ]',
    '}',
    'Chỉ trả về JSON, KHÔNG thêm gì khác.',
  ].join('\n')),

  [TASK_TYPES.ARC_CHAPTER_DRAFT]: [
    'Viết nội dung chi tiết cho ĐÚNG 1 chương dựa trên dàn ý đã cho.',
    'Bám sát tóm tắt và sự kiện chính của chương này.',
    'Viết chi tiết đủ dùng: hành động, tâm lý, đối thoại, miêu tả cảnh vật, nhưng không padding.',
    'Mục tiêu độ dài theo yêu cầu/dàn ý; nếu không có, hoàn chỉnh một chương hoặc một phần chương có điểm dừng tự nhiên.',
    'KHÔNG tự ý thêm sự kiện ngoài dàn ý.',
    'Tôn trọng objective_refs, anchor_refs, continuity_in, conflict, decision_or_consequence, state_changes, continuity_out, pacing và arc_guard_note nếu được cung cấp; không được viết vượt mức đại cục cho phép.',
    'current_status/Character Live Canon ưu tiên hơn personality: personality là nền, current_status là ràng buộc đang tác động ngay trong chương này.',
    'Nếu có [ANCHOR BẮT BUỘC CHO CHƯƠNG NÀY] thì chapter này PHẢI đạt đúng các yêu cầu đó. Nếu có [ANCHOR CHƯA ĐẾN HẠN] thì không được payoff sớm các anchor đó.',
    'KHÔNG được viết lại thành cảnh chính những gì đã xảy ra ở các chương trước; chỉ được nhắc lại rất ngắn nếu cần.',
    'Mỗi cảnh phải là hệ quả tiếp nối từ chương trước và tạo một độ chuyển động rõ: thông tin, quan hệ, cảm xúc, lựa chọn, nhịp hài hoặc trạng thái mới.',
    'BẮT BUỘC trước khi xuất chương phải tự kiểm tra timeline, án phạt/giam giữ/thương tích, lộ tu vi/bảo vật/năng lực, và phản ứng hợp lý của nhân vật phụ/phía đối địch.',
    'Chỉ trả về nội dung chương, KHÔNG thêm tiêu đề hay ghi chú.',
  ].join('\n'),
  [TASK_TYPES.GENERATE_MACRO_MILESTONES]: withPlanningAndCanonPrefix([
    'Hoạch định ĐÚNG số lượng cột mốc đại cục được yêu cầu cho đúng PHẠM VI LẬP KẾ HOẠCH được cung cấp; mỗi cột mốc là một điểm ngoặt LỚN của hành trình.',
    'Nếu đầu vào có [SỐ LƯỢNG CỘT MỐC CẦN TẠO] thì mảng milestones PHẢI có đúng bằng đó phần tử; không được tự ý rơi về một con số mặc định.',
    'Phải phân biệt rõ GIỮA tổng độ dài dự kiến của toàn truyện và phạm vi chapter đang được yêu cầu lập đại cục.',
    'Nếu phạm vi lập kế hoạch không bắt đầu từ Chương 1 thì KHÔNG được tự ý kéo cột mốc về Chương 1 và KHÔNG được coi phạm vi đó là toàn bộ truyện.',
    'Cần phân bố hợp lý trong phạm vi được giao, có leo thang, khủng hoảng, đảo chiều và trả giá rõ ràng.',
    'Nếu tác giả có yêu cầu riêng, ưu tiên tối đa theo yêu cầu đó.',
    'Mỗi cột mốc bắt buộc phải trả về thêm một contract có cấu trúc để hệ thống dùng cho planner và validator, không chỉ mô tả bằng văn tự do.',
    'Nếu đầu vào có [YÊU CẦU BẮT BUỘC THEO CHƯƠNG], cột mốc chứa chapter đó PHẢI đưa các yêu cầu này vào chapter_anchors trong contract; không được chỉ nhắc trong description.',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "milestones": [',
    '    {',
    '      "order": 1,',
    '      "title": "Tên cột mốc",',
    '      "description": "Mô tả 2-3 câu",',
    '      "chapter_from": 1,',
    '      "chapter_to": 80,',
    '      "emotional_peak": "Cảm xúc cần đạt",',
    '      "contract": {',
    '        "narrative_summary": "Nội dung cốt lõi của cột mốc",',
    '        "objectives": [',
    '          { "id": "OBJ1", "text": "Mục tiêu cốt lõi", "focus_characters": ["Nhân vật A"] }',
    '        ],',
    '        "target_states": [',
    '          { "character": "Nhân vật A", "state": "Trạng thái đích tối đa được phép" }',
    '        ],',
    '        "focused_characters": ["Nhân vật A", "Nhân vật B"],',
    '        "forbidden_outcomes": ["Kết quả không được xảy ra trong cột mốc này"],',
    '        "max_relationship_stage": 1,',
    '        "chapter_anchors": [',
    '          { "id": "ANCHOR1", "target_chapter": 25, "strictness": "hard", "requirement_text": "Điều bắt buộc phải xảy ra", "objective_refs": ["OBJ1"], "focus_characters": ["Nhân vật A"], "success_signals": ["Tín hiệu thành công"], "forbid_before": true, "notes": "" }',
    '        ]',
    '      }',
    '    }',
    '  ]',
    '}',
    'Chỉ trả về JSON.',
  ].join('\n')),
  [TASK_TYPES.ANALYZE_MACRO_CONTRACT]: withPlanningAndCanonPrefix([
    'Phân tích ĐÚNG 1 cột mốc đại cục và chuyển nó thành contract có cấu trúc để planner/validator có thể dùng trực tiếp.',
    'Đây là bước chuẩn hóa ý đồ tác giả, không phải viết lại cột mốc cho đẹp hơn.',
    'Phải bám sát nội dung cột mốc được cung cấp; không tự ý đẩy nhanh tình tiết, không tự ý thêm payoff, không tự ý nâng mức quan hệ/plot lên cao hơn nếu đầu vào chưa nói.',
    'Nếu đầu vào mơ hồ, hãy đặt objective và target_state ở mức BẢO THỦ, ưu tiên buildup/an toàn hơn là overshoot.',
    'Nếu có phần "mục tiêu", "kết quả", "tình trạng", "trạng thái" trong text đầu vào, phải ưu tiên đọc đúng các phần đó.',
    'Nếu đầu vào có chapter_anchors hoặc yêu cầu bắt buộc theo chapter, phải giữ lại và chuẩn hóa thành chapter_anchors có cấu trúc; không được làm mất.',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "contract": {',
    '    "narrative_summary": "Nội dung cốt lõi của cột mốc",',
    '    "objectives": [',
    '      { "id": "OBJ1", "text": "Mục tiêu cốt lõi", "focus_characters": ["Nhân vật A"] }',
    '    ],',
    '    "target_states": [',
    '      { "character": "Nhân vật A", "state": "Trạng thái đích tối đa được phép" }',
    '    ],',
    '    "focused_characters": ["Nhân vật A", "Nhân vật B"],',
    '    "forbidden_outcomes": ["Kết quả không được xảy ra trong cột mốc này"],',
    '    "max_relationship_stage": 1,',
    '    "chapter_anchors": [',
    '      { "id": "ANCHOR1", "target_chapter": 25, "strictness": "hard", "requirement_text": "Điều bắt buộc phải xảy ra", "objective_refs": ["OBJ1"], "focus_characters": ["Nhân vật A"], "success_signals": ["Tín hiệu thành công"], "forbid_before": true, "notes": "" }',
    '    ]',
    '  },',
    '  "warnings": ["Cảnh báo nếu đầu vào quá mơ hồ, nếu không thì mảng rỗng"]',
    '}',
    'Chỉ trả về JSON.',
  ].join('\n')),
  [TASK_TYPES.AUDIT_ARC_ALIGNMENT]: withPlanningAndCanonPrefix([
    'Kiểm tra độ lệch giữa những chương gần đây và đại cục/arc hiện tại.',
    'Chỉ ra độ lệch cụ thể, không nói chung chung.',
    'Trả về CHÍNH XÁC JSON format sau:',
    '{',
    '  "aligned": true,',
    '  "drift_score": 0,',
    '  "issues": ["Vấn đề 1"],',
    '  "suggestions": ["Đề xuất 1"],',
    '  "current_position": "Tóm tắt vị trí hiện tại của truyện trong 1 câu"',
    '}',
    'Chỉ trả về JSON.',
  ].join('\n')),
};
