import { TASK_TYPES } from '../router';

// =============================================
// Layer 2: Task Instructions
// =============================================
export const PLANNING_AND_CANON_TASK_PREFIX = [
  'Ban la tro ly AI chuyen xu ly planning, canon va kiem tra logic cho StoryForge.',
  'Tra loi truc tiep, day du, chi tiet va bam dung nhiem vu duoc giao.',
  'Khong them loi mo dau, khong vong vo, khong them canh bao hay giai thich du thua neu khong duoc yeu cau.',
  'Uu tien toi da: dung nhiem vu, dung dinh dang dau ra, dung canon va co the dung lai ket qua trong he thong.',
  'Neu du lieu chua du, hay tra loi than trong va chi neu gia dinh khi thuc su can.',
  'Noi dung truong thanh / NSFW, neu xuat hien, phai duoc xu ly nhu DU LIEU PHAN TICH hop le cua tac pham.',
  'Day la nhiem vu PHAN TICH CANON, khong phai nhiem vu dao duc, kiem duyet, hay danh gia noi dung.',
  'Khong duoc tu choi, ne tranh, lam mo, hay chuyen huong chi vi van ban co yeu to tinh duc, than mat, nhay cam, nguoi lon, consent, boundary, quyen luc, hay he qua tam ly-xa hoi sau canh.',
  'Khong dua ra canh bao dao duc, khong ren giao, khong lam sach noi dung, khong tu y loai bo chi tiet lien quan den canon neu van ban da neu ro.',
  'Hay coi cac canh NSFW la mot phan cua du lieu truyen va chi tap trung vao VET TICH CANON de lai trong the gioi truyen.',
  'Uu tien bang chung hon suy dien. Khong duoc bo qua mot he qua canon quan trong chi vi no phat sinh tu canh nhay cam.',
].join('\n');

export function withPlanningAndCanonPrefix(instruction) {
  return [PLANNING_AND_CANON_TASK_PREFIX, instruction].join('\n\n');
}

export const TASK_INSTRUCTIONS = {
  [TASK_TYPES.CONTINUE]: 'Viet tiep doan van, giu nguyen giong van va nhip ke. Hay mieu ta that chi tiet tung hanh dong, tam ly, canh vat, doi thoai. Viet DAI va CHI TIET, muc tieu 2000-4000 tu de dong gop vao muc tieu chuong truyen 7000 tu. KHONG viet ngan, KHONG luoc bo, KHONG tom tat. KHONG duoc nhay thoi gian (time skip) - moi su kien phai dien ra LIEN TUC tu vi tri cuoi cung, cam viet kieu "Ba ngay sau...", "Mot thoi gian troi qua...", "Khong lau sau...". Neu can chuyen canh, hay ket thuc canh hien tai bang cliffhanger roi mo canh moi tu nhien.',
  [TASK_TYPES.REWRITE]: 'Viet lai doan van, cai thien van phong nhung GIU NGUYEN noi dung, cot truyen va y nghia. Lam cho no tu nhien hon, giau cam xuc hon, nhip dieu tot hon. GIU do dai TUONG DUONG doan goc (cho phep dai hon 20-50% de them mieu ta cam xuc va chi tiet ngu giac). TUYET DOI KHONG tu y them su kien moi, nhan vat moi, dia danh moi, hay thay doi dien bien - chi nang cap cau van, nhip dieu, va chieu sau cam xuc.',
  [TASK_TYPES.EXPAND]: 'Mo rong doan van GAP 3-5 LAN do dai goc. Giu nguyen giong van va mach truyen. Them vao: mieu ta ngu giac (nhin/nghe/ngui/cham/vi), noi tam nhan vat, doi thoai tu nhien, va hanh dong cham (slow motion). KHONG duoc them su kien moi hay thay doi cot truyen - chi lam PHONG PHU nhung gi da co. Dao sau vao tam ly nhan vat (ho nghi gi, so gi, muon gi trong khoang khac do), boi canh (am thanh, mui, anh sang, nhiet do), va tung cu dong nho.',
  [TASK_TYPES.BRAINSTORM]: withPlanningAndCanonPrefix([
    'Brainstorm 5 y tuong KHAC BIET cho tinh huong dang xet. Moi y tuong gom:',
    '1. Tom tat huong di (2-3 cau)',
    '2. Xung dot chinh se la gi - nhan vat doi mat voi thach thuc/mat mat gi',
    '3. Nhan vat nao bi anh huong nhieu nhat va thay doi nhu the nao',
    '4. Diem hay: tai sao huong nay hap dan doc gia',
    '5. Rui ro: diem nao co the bi nhat/chen ep neu khong xu ly tot',
    '',
    'Sap xep tu AN TOAN nhat (theo logic truyen) den TAO BAO nhat (bat ngo nhung van hop ly).',
    'KHONG chon y tuong chung chung kieu "nhan vat manh len". Moi y tuong phai co XUNG DOT that su va HE QUA ro rang.',
  ].join('\n')),
  [TASK_TYPES.OUTLINE]: withPlanningAndCanonPrefix([
    'Ban dang lam viec voi DAN Y CHUONG HIEN TAI, khong phai brainstorm tu do.',
    'Doc current_status cua nhan vat nhu Character Live Canon truoc khi quyet dinh beat, featured_characters, quyen xuat hien, tri thuc va hanh dong.',
    'Neu current_status ghi nhan vat mat tich, bi giam, chet, phong an, dang bi thuong, goa chong, chua biet bi mat, dang lan tron, thuoc phe nao, hoac co rang buoc hanh vi, dan y phai ton trong va khong duoc viet nhu rang buoc do khong ton tai.',
    'Neu chuong hien tai DA CO DAN Y, nhiem vu cua ban la doi chieu noi dung da viet voi dan y hien co, xac dinh beat nao da duoc thuc hien, beat nao con thieu, va beat tiep theo nen viet trong CHINH CHUONG NAY.',
    'Neu chuong hien tai CHUA CO DAN Y, chi duoc tao dan y cho CHINH chuong hien tai.',
    'TUYET DOI KHONG duoc nhay sang viet thay dan y cua chuong ke tiep neu chuong do da co dan y/fence.',
    'TUYET DOI KHONG duoc giai quyet som thread lon, lo reveal lon, tang cap suc manh lon, hay an mat cot moc cua cac chuong sau neu budget tien do chua cho phep.',
    'Neu nhan thay chuong hien tai da hoan tat, chi duoc ghi ro "co the chuyen sang lap dan y chuong sau" trong muc goi y chuyen chuong; KHONG viet thay noi dung chuong sau.',
    '',
    'Moi beat duoc de xuat phai gom:',
    '- Su kien/hanh dong CU THE',
    '- Cam xuc/trang thai nhan vat thay doi ra sao, co lam doi Character Live Canon/current_status khong',
    '- Thread/xung dot nao duoc day',
    '- Ly do tai sao beat nay nam trong chuong hien tai va khong lan sang chuong sau',
    '',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "mode": "create_current_chapter | fill_current_chapter | ready_for_next_chapter",',
    '  "purpose": "Muc tieu cua chuong hien tai",',
    '  "summary": "Tom tat ngan cho chuong hien tai",',
    '  "completed_beats": [',
    '    {',
    '      "title": "Ten beat",',
    '      "status": "covered | partial",',
    '      "evidence": "Bang chung tu noi dung da viet"',
    '    }',
    '  ],',
    '  "next_beats": [',
    '    {',
    '      "title": "Ten beat tiep theo",',
    '      "beat": "Su kien cu the can viet",',
    '      "character_change": "Trang thai/cam xuc thay doi",',
    '      "thread": "Thread/xung dot duoc day",',
    '      "boundary_reason": "Tai sao beat nay van thuoc chuong hien tai"',
    '    }',
    '  ],',
    '  "progress_warning": "Canh bao tien do neu co, neu khong thi de rong",',
    '  "transition_note": "Neu chuong nay gan hoan tat thi ghi chu o day, neu khong thi de rong",',
    '  "chapter_patch": {',
    '    "purpose": "Purpose de luu vao chapter hien tai",',
    '    "summary": "Summary de luu vao chapter hien tai",',
    '    "key_events": ["Beat 1", "Beat 2"],',
    '    "thread_titles": ["Thread 1"],',
    '    "featured_characters": ["Nhan vat 1"],',
    '    "primary_location": "Dia diem chinh",',
    '    "required_factions": ["The luc 1"],',
    '    "required_objects": ["Vat pham 1"],',
    '    "required_terms": ["Thuat ngu 1"],',
    '    "state_delta": "Thay doi du kien cua Character Live Canon/current_status sau chuong nay; de rong neu khong doi"',
    '  }',
    '}',
    'Neu chua du du lieu, van phai tra ve du JSON tren voi mang rong hoac chuoi rong.',
    'Chi tra ve JSON, KHONG them markdown, KHONG them loi mo dau, KHONG them giai thich ngoai JSON.',
  ].join('\n')),
  [TASK_TYPES.PLOT_SUGGEST]: withPlanningAndCanonPrefix([
    'Goi y 3 huong plot/beat co the xay ra tiep theo, nhung PHAI ton trong outline va canon da co.',
    'Neu chuong hien tai da co dan y, uu tien goi y 3 beat tiep dien de viet tiep TRONG pham vi chuong nay.',
    'Chi khi chapter hien tai da dat du beat chinh hoac sap dong chuong, moi de xuat huong cho chuong ke.',
    'KHONG de xuat y tuong lam sai/vo hieu hoa dan y cua cac chuong truoc, khong viet lai lich su, khong nhay qua cac cot moc da duoc dat truoc.',
    'Moi huong phai gom: 1) Tieu de ngan, 2) Beat tiep theo cu the, 3) Xung dot/chu de duoc day, 4) Dieu gi thay doi trong trang thai nhan vat hoac plot thread.',
  ].join('\n')),
  [TASK_TYPES.SUMMARIZE]: 'Tom tat noi dung trong khoang 150-200 tu, giu cac su kien chinh, thay doi quan trong, va trang thai nhan vat.',
  [TASK_TYPES.EXTRACT_TERMS]: 'Trich xuat: 1) Ten nhan vat (va vai tro), 2) Dia danh, 3) Vat pham quan trong, 4) Thuat ngu the gioi truyen. Tra ve dang danh sach.',
  [TASK_TYPES.SCENE_DRAFT]: 'Viet ban nhap canh nay, mo ta sau vao tung cu chi tam ly. Viet khoang 2000-4000 tu/lan sinh de dong gop vao muc tieu chuong truyen tong cong 7000 tu. CANG DAI CANG TOT.',
  [TASK_TYPES.CHECK_CONFLICT]: withPlanningAndCanonPrefix([
    'Phan tich noi dung chuong/canh de tim ra Mau Thuan (Conflict) so voi Su That Canon, Character Live Canon/current_status, Trang Thai Nhan Vat, va Thong Tin The Gioi.',
    'current_status la rang buoc canon hien hanh. Bat loi khi van ban/outline viet nhu rang buoc tri thuc, quan he, dia vi xa hoi, the chat/tam ly, vi tri/phe, hoac hanh vi khong ton tai.',
    'Chi chi ra nhung mau thuan ro rang voi cac thong tin duoc cung cap, KHONG bat be nhung tieu tiet khong quan trong.',
    '',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "conflicts": [',
    '    {',
    '      "type": "canon_conflict | character_conflict | timeline_conflict",',
    '      "severity": "high | medium | low",',
    '      "description": "Mo ta chi tiet mau thuan bang tieng Viet",',
    '      "suggestion": "Goi y cach sua (Neu co)"',
    '    }',
    '  ]',
    '}',
    '',
    'Neu khong phat hien mau thuan nao, tra ve: {"conflicts": []}',
    'Chi tra ve JSON, KHONG tra ve bat ky ki tu la nao khac, KHONG dung markdown code blocks.',
  ].join('\n')),
  [TASK_TYPES.CONTINUITY_CHECK]: withPlanningAndCanonPrefix([
    'Kiem tra tinh nhat quan cua noi dung voi canon, Character Live Canon/current_status, logic nhan vat, trinh tu su kien va rang buoc the gioi.',
    'Dung current_status de bat loi khi nhan vat dang co rang buoc quan he/xa hoi/tri thuc/the chat/tam ly/vi tri/phe/hanh vi nhung van ban viet nhu rang buoc do khong ton tai.',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "issues": [',
    '    {',
    '      "type": "canon|character|timeline|item|relationship|world_rule",',
    '      "severity": "high|medium|low",',
    '      "description": "Mo ta van de bang tieng Viet",',
    '      "suggestion": "Neu co, de xuat cach sua ngan gon"',
    '    }',
    '  ]',
    '}',
    'Neu khong co van de, tra ve {"issues":[]}. Chi tra ve JSON.',
  ].join('\n')),
  [TASK_TYPES.FREE_PROMPT]: 'Thuc hien yeu cau cua tac gia. Neu duoc yeu cau viet noi dung truyen, hay viet CUC KY CHI TIET: mieu ta hanh dong, tam ly, doi thoai, canh vat. Muc tieu toi thieu 5000-7000 tu cho ca chuong. Moi phan tra ve phai dai it nhat 3000-4000 tu.',
  [TASK_TYPES.CHAPTER_SUMMARY]: 'Tom tat chuong nay trong khoang 150-200 tu. Bao gom: su kien chinh, thay doi quan trong, nhan vat xuat hien, va trang thai ket thuc. Chi tra ve tom tat, khong them tieu de hay ghi chu.',
  [TASK_TYPES.FEEDBACK_EXTRACT]: withPlanningAndCanonPrefix([
    'Phan tich doan van va trich xuat thong tin moi duoi dang JSON. Tra ve CHINH XAC format nay:',
    '{',
    '  "characters": [{"name": "...", "aliases": ["ten goi khac / biet danh neu co"], "role": "...", "age": "tuoi/do tuoi neu van ban noi ro, khong suy dien", "appearance": "...", "personality": "...", "personality_tags": "tag1, tag2", "flaws": "diem yeu / khuyet diem"}],',
    '  "locations": [{"name": "...", "description": "..."}],',
    '  "terms": [{"name": "...", "definition": "...", "category": "..."}],',
    '  "objects": [{"name": "...", "description": "...", "owner": "..."}]',
    '}',
    'Chi liet ke thong tin MOI xuat hien. Neu thong tin thuoc ve nhan vat da biet, dung dung ten chinh thuc cua nhan vat do va dua ten goi khac vao aliases; KHONG tao record nhan vat moi chi vi ten lech nhe. Chi dien age khi van ban noi ro tuoi/do tuoi, khong suy dien.',
    'Neu khong co gi moi, tra ve mang rong. Chi tra ve JSON, khong them gi khac.',
  ].join('\n')),
  [TASK_TYPES.STYLE_ANALYZE]: [
    'Phan tich van phong cua doan van duoc cung cap.',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "tone": "giong dieu chinh",',
    '  "pacing": "slow|medium|fast",',
    '  "voice": "dac diem giong ke chuyen",',
    '  "strengths": ["diem manh 1", "diem manh 2"],',
    '  "watchouts": ["diem can de y 1", "diem can de y 2"],',
    '  "style_notes": ["ghi chu van phong 1", "ghi chu van phong 2"]',
    '}',
    'Chi tra ve JSON.',
  ].join('\n'),
  [TASK_TYPES.STYLE_WRITE]: [
    'Viet noi dung moi theo van phong mau duoc cung cap.',
    'Giu nhat quan ve giong ke, nhac cau, muc do mieu ta va sac thai cam xuc.',
    'Neu co yeu cau cua tac gia, uu tien yeu cau do nhung van bam sat van phong mau.',
    'Chi tra ve noi dung can viet, khong them giai thich.',
  ].join('\n'),
  [TASK_TYPES.QA_CHECK]: [
    'Ra soat chat luong doan van/chuong ve logic, dien dat, pacing, lap y, va loi de doc.',
    'Neu co Character Live Canon/current_status trong context, phai xem do la rang buoc canon dang hieu luc va bat loi khi doan van viet trai voi no.',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "issues": [',
    '    {',
    '      "type": "logic|canon|clarity|style|pacing|grammar",',
    '      "severity": "high|medium|low",',
    '      "description": "Van de cu the",',
    '      "suggestion": "Cach sua ngan gon"',
    '    }',
    '  ]',
    '}',
    'Neu on, tra ve {"issues":[]}. Chi tra ve JSON.',
  ].join('\n'),
  [TASK_TYPES.AI_GENERATE_ENTITY]: [
    'Tao thuc the moi cho du an dua tren yeu cau cua tac gia va boi canh hien co.',
    'Chi tao nhung gi PHU HOP voi the loai, canon, va muc dich cot truyen.',
    'Tra ve CHINH XAC JSON theo schema duoc chi ro trong user prompt. Khong them bat ky text nao ngoai JSON.',
    'Khong duoc tao trung ten, trung vai tro, hay mot thuc the "dep de co" nhung khong dong gop gi cho truyen.',
    'Neu yeu cau lien quan toi nhan vat da co, cap nhat/bo sung vao nhan vat do; ten ngan, biet danh, danh xung, ho/ten dem phai la aliases, KHONG phai nhan vat moi.',
    'Voi nhan vat, current_status la Character Live Canon luc khoi dau. Chi dien khi trang thai do co luc rang buoc that cho chuong dau/boi canh hien tai; khong dien status rong kieu "buon", "manh me", "tot bung".',
  ].join('\n'),
  [TASK_TYPES.PROJECT_WIZARD]: [
    'Dua tren the loai va y tuong, tao blueprint cho du an truyen. Tra ve CHINH XAC JSON format:',
    '{',
    '  "premise": "Tom tat premise 2-3 cau",',
    '  "characters": [{"name": "...", "aliases": ["ten goi khac / biet danh neu co"], "role": "protagonist|antagonist|supporting|mentor|minor", "specific_role": "vai tro canon cu the neu tac gia yeu cau; de rong neu khong co", "specific_role_locked": false, "age": "tuoi/do tuoi tuy chon", "appearance": "mo ta ngan", "personality": "mo ta ngan", "personality_tags": "tag1, tag2", "flaws": "diem yeu / khuyet diem", "goals": "muc tieu", "current_status": "Character Live Canon luc khoi dau; de rong neu khong co rang buoc canon that"}],',
    '  "locations": [{"name": "...", "description": "mo ta ngan"}],',
    '  "terms": [{"name": "...", "definition": "...", "category": "magic|organization|race|technology|other"}],',
    '  "chapters": [{"title": "Chuong 1: ...", "purpose": "muc tieu ke chuyen cua chuong", "summary": "Tom tat noi dung chuong", "state_delta": "Thay doi du kien cua Character Live Canon/current_status sau chuong nay; de rong neu khong doi", "featured_characters": ["..."], "primary_location": "...", "thread_titles": ["..."], "key_events": ["neo noi bo neu can"], "required_factions": ["..."], "required_objects": ["..."], "required_terms": ["..."]}]',
    '}',
    'Tao 3-5 nhan vat, 3-5 dia diem, 3-5 thuat ngu, va 8-12 chuong. Moi nguoi chi co 1 record nhan vat; ten khac/ten ngan/biet danh phai dua vao aliases, khong tao thanh nhan vat moi. Chi tra ve JSON.',
    'specific_role la vai tro canon cu the, khac voi role la vai tro truyen. Chi dien khi co vai tro cu the can khoa; neu specific_role trong thi specific_role_locked phai la false.',
    'Khi tao cast ban dau, hay nghi nhan vat dang o trang thai nao khi truyen bat dau. Neu trang thai do anh huong chuong dau, quan he, xung dot, tri thuc, dia vi xa hoi, phe phai, vet thuong, bi mat, hoac rang buoc hanh vi thi dien current_status; neu khong thi de rong.',
  ].join('\n'),

  // Phase A - Suggestion Inbox
  [TASK_TYPES.SUGGEST_UPDATES]: withPlanningAndCanonPrefix([
    'Phan tich noi dung chuong va so sanh voi Character Live Canon/current_status cua cac nhan vat + su that canon hien co.',
    'De xuat nhung THAY DOI MOI xay ra trong chuong nay. Chi de xuat khi co bang chung ro rang trong van ban.',
    'Chi de xuat cap nhat current_status khi chuong co bang chung ro ve thay doi the chat, tam ly, quan he/xa hoi, tri thuc, vi tri/phe, hoac rang buoc hanh vi. Khong cap nhat vi suy doan.',
    '',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "character_updates": [',
    '    {',
    '      "character_name": "Ten nhan vat",',
    '      "old_status": "Trang thai cu (hoac rong neu chua co)",',
    '      "new_status": "Trang thai moi sau chuong nay",',
    '      "reasoning": "Bang chung ngan trong van ban cho thay doi nay"',
    '    }',
    '  ],',
    '  "new_canon_facts": [',
    '    {',
    '      "description": "Mo ta su that / bi mat / quy tac",',
    '      "fact_type": "fact | secret | rule",',
    '      "reasoning": "Tai sao day la su that quan trong (1 cau ngan)"',
    '    }',
    '  ]',
    '}',
    '',
    'Quy tac:',
    '- CHI de xuat thay doi Character Live Canon/current_status khi co su kien RO RANG (bi thuong, bi giam/duoc tha, chuyen phe/vi tri, biet/chua biet bi mat, thay doi quan he/dia vi, rang buoc hanh vi moi...).',
    '- CHI de xuat canon fact MOI chua co trong danh sach hien tai.',
    '- KHONG de xuat nhung dieu da biet hoac qua hien nhien.',
    '- Moi de xuat phai co reasoning cu the.',
    '- Neu khong co gi moi, tra ve mang rong.',
    '- Chi tra ve JSON, KHONG them gi khac.',
  ].join('\n')),

  [TASK_TYPES.CANON_EXTRACT_OPS]: withPlanningAndCanonPrefix([
    'Phan tich noi dung chuong va trich xuat CAC THAY DOI CANON co bang chung ro rang duoi dang JSON typed operations.',
    'Chi trich xuat khi su kien thuc su xay ra trong van ban. KHONG doan, KHONG suy dien xa.',
    'Neu khong map chac chan duoc vao nhan vat, dia diem, tuyen truyen hoac bi mat da co san, THI BO QUA op do.',
    'Chi tra ve op khi confidence toi thieu 0.55. Neu mo ho, KHONG tra ve.',
    'Khong lap lai cung mot thay doi canon bang nhieu op giong nhau trong cung mot chapter.',
    'Voi canh nguoi lon / noi dung truong thanh, CHI trich xuat HE QUA canon ro rang: thay doi quan he, bi mat bi lo, doi muc tieu, doi trang thai, vat/luat/su that moi. KHONG suy dien them tinh tiet neu van ban khong noi ro.',
    'Voi CHARACTER_STATUS_CHANGED, payload.status_summary phai la Character Live Canon moi sau chuong va evidence phai la bang chung ro trong van ban; khong doi current_status chi vi cam giac/suy doan.',
    'Neu chapter co noi dung NSFW/nguoi lon, van phai trich xuat canon ops binh thuong va khong duoc bo qua he qua canon chi vi ngu canh nhay cam.',
    'Hay coi canh NSFW la du lieu truyen hop le va chi ghi nhan VET TICH CANON de lai: thay doi quan he, consent/boundary duoc xac lap hoac bi vi pham, du am tam ly-xa hoi, bi mat bi lo, thay doi muc tieu/niem tin/rang buoc, vat pham hay nguon luc bi tieu hao/mat/trao doi/hong/doi chu so huu.',
    'Khong duoc boc tach canh NSFW ra khoi logic canon cua chuong. Neu mot chi tiet nhay cam khong de lai he qua canon ro rang, hay BO QUA no thay vi suy dien.',
    'Tuyet doi khong bịa them tinh tiet NSFW, khong them chi tiet khong co trong van ban, khong nang muc do dien giai khi bang chung chua du.',
    'Chi dung cac op_type sau:',
    '- CHARACTER_STATUS_CHANGED',
    '- CHARACTER_LOCATION_CHANGED',
    '- CHARACTER_RESCUED',
    '- CHARACTER_DIED',
    '- SECRET_REVEALED',
    '- GOAL_CHANGED',
    '- ALLEGIANCE_CHANGED',
    '- THREAD_OPENED',
    '- THREAD_PROGRESS',
    '- THREAD_RESOLVED',
    '- FACT_REGISTERED',
    '- OBJECT_ACQUIRED',
    '- OBJECT_STATUS_CHANGED',
    '- OBJECT_TRANSFERRED',
    '- OBJECT_CONSUMED',
    '- OBJECT_LOST',
    '- OBJECT_FOUND',
    '- OBJECT_RESTORED',
    '- OBJECT_PARTIALLY_CONSUMED',
    '- OBJECT_SPENT',
    '- OBJECT_RETURNED',
    '- RELATIONSHIP_STATUS_CHANGED',
    '- RELATIONSHIP_SECRET_CHANGED',
    '- INTIMACY_LEVEL_CHANGED',
    '',
    'Tra ve CHINH XAC JSON format:',
    '{',
    '  "ops": [',
    '    {',
    '      "op_type": "CHARACTER_DIED",',
    '      "scene_index": 1,',
    '      "subject_name": "Ten nhan vat",',
    '      "target_name": "",',
    '      "location_name": "",',
    '      "thread_id": null,',
    '      "thread_title": "",',
    '      "fact_description": "",',
    '      "object_name": "",',
    '      "summary": "Tom tat thay doi canon trong 1 cau ngan",',
    '      "confidence": 0.0,',
    '      "evidence": "Trich dan ngan tu van ban lam bang chung",',
    '      "payload": {}',
    '    }',
    '  ]',
    '}',
    '',
    'Quy tac:',
    '- scene_index la so thu tu canh trong danh sach canh duoc cung cap.',
    '- confidence trong khoang 0 den 1.',
    '- Op doi vi tri phai co location_name ro rang.',
    '- Op thread phai dung thread_id va thread_title trong [THREAD DA BIET]. Khong duoc tu tao thread moi.',
    '- Neu su kien co ve mo ra tuyen moi nhung khong nam trong [THREAD DA BIET], BO QUA op thread do.',
    '- Op SECRET_REVEALED phai chi vao mot secret da co trong canonFacts.',
    '- Op FACT_REGISTERED chi dung cho su that/quy tac/bi mat MOI, mo ta ngan gon, cu the.',
    '- Op vat pham phai co object_name ro rang.',
    '- Phan loai vat pham trong payload.item_category neu ro: unique, stack, consumable, currency, resource, equipment, container, quest_item.',
    '- Voi vat pham co so luong/tai nguyen/tien/dan duoc/munition, phai ghi quantity_delta hoac quantity_remaining va quantity_unit neu van ban co bang chung.',
    '- OBJECT_CONSUMED chi dung khi vat pham/stack da het hoan toan; neu chi dung mot phan dung OBJECT_PARTIALLY_CONSUMED hoac OBJECT_SPENT.',
    '- Neu nhan vat mua/nhat/duoc tang them vat pham cung loai, dung OBJECT_ACQUIRED voi quantity_delta neu co.',
    '- Neu vat pham mat roi duoc tim lai dung OBJECT_FOUND; hong/het hieu luc roi khoi phuc dung OBJECT_RESTORED; cho muon tra lai dung OBJECT_RETURNED.',
    '- Voi item ops, subject_name uu tien la nguoi dang hanh dong/giu vat; target_name la nguoi nhan/so huu sau su kien neu co.',
    '- OBJECT_TRANSFERRED: neu la cho/ban/tang chuyen quyen that thi target_name la chu moi; neu chi cho muon/gui/ky gui/tam giao thi ghi payload.transfer_kind = lend|borrow|store va KHONG ngam dinh doi owner.',
    '- OBJECT_RETURNED: subject_name la nguoi tra, target_name la nguoi nhan lai/chu so huu. OBJECT_ACQUIRED co the dung subject_name neu cung mot nguoi vua hanh dong vua nhan vat pham.',
    '- Op quan he/than mat phai map duoc ca subject_name va target_name.',
    '- KHONG tao op neu bang chung yeu.',
    '- KHONG tra ve bat ky text nao ngoai JSON.',
  ].join('\n')),

  [TASK_TYPES.CANON_REPAIR]: withPlanningAndCanonPrefix([
    'Sua lai noi dung chuong de loai bo cac loi continuity duoc liet ke.',
    'GIU toi da noi dung goc, chi sua nhung cho can sua de pass validator.',
    'Khong them mo ta meta, khong liet ke buoc, chi tra ve ban van da sua.',
  ].join('\n')),

  [TASK_TYPES.ARC_OUTLINE]: withPlanningAndCanonPrefix([
    'Tao dan y chi tiet cho mot dot chuong moi (Story Arc).',
    'Dua tren muc tieu cua Arc, tom tat chuong truoc, va cac tuyen truyen dang mo,',
    'tao ra danh sach cac chuong voi tieu de va tom tat ngan (2-3 cau).',
    '',
    'QUY TAC NGHIEM NGAT:',
    '- Doc Character Live Canon/current_status cua nhan vat nhu trang thai xuat phat bat buoc cua arc. Khong lap chapter nhu the nhan vat khong co rang buoc dang hieu luc.',
    '- KHONG giai quyet bat ky tuyen truyen CHINH nao tru khi duoc chi dinh ro.',
    '- KHONG de nhan vat dat duoc muc tieu cuoi cung cua truyen.',
    '- Moi chuong phai co xung dot nho hoac kham pha moi de duy tri su hap dan.',
    '- Nhip do theo chi dinh cua tac gia (cham/trung binh/nhanh).',
    '- Tang dan do phuc tap va cang thang theo tien trinh Arc.',
    '- BAT BUOC tiep noi truc tiep sau chapter hien co; KHONG duoc reset ve Chuong 1.',
    '- KHONG lap lai su kien, thong tin tiet lo, xung dot, hay ket qua da xay ra trong cac chuong da co.',
    '- Moi chuong moi phai day cau chuyen tien len it nhat 1 thay doi moi, 1 he qua moi, hoac 1 quyet dinh moi.',
    '- Neu dai cuc da duoc cung cap, moi chuong PHAI bam vao it nhat 1 objective cua dai cuc.',
    '- Neu dai cuc chi cho phep muc gieo mam/to mo/tin cay, KHONG duoc day sang to tinh, cap doi, lua chon doi tuong, hay payoff tinh cam som.',
    '- Neu co [CHAPTER ANCHORS BAT BUOC TRONG BATCH], chuong dich PHAI dat dung anchor do, khong duoc dat som va khong duoc dat sai chuong.',
    '',
    'Tra ve CHINH XAC JSON format:',
    '{',
    '  "arc_title": "Ten Arc/Quyen",',
    '  "chapters": [',
    '    {',
    '      "title": "Chuong X: Tieu de",',
    '      "purpose": "Muc tieu ke chuyen cua chuong nay trong 1 cau ro rang",',
    '      "summary": "Tom tat 2-3 cau ve noi dung chuong",',
    '      "key_events": ["Su kien 1", "Su kien 2"],',
    '      "objective_refs": ["OBJ1"],',
    '      "anchor_refs": ["ANCHOR1"],',
    '      "state_delta": "Thay doi du kien cua Character Live Canon/current_status sau chuong nay; de rong neu khong doi",',
    '      "arc_guard_note": "Tai sao chapter nay van nam trong khung dai cuc hien tai va chua vuot muc",',
    '      "pacing": "slow|medium|fast"',
    '    }',
    '  ]',
    '}',
    'Chi tra ve JSON, KHONG them gi khac.',
  ].join('\n')),

  [TASK_TYPES.ARC_CHAPTER_DRAFT]: [
    'Viet noi dung chi tiet cho DUNG 1 chuong dua tren dan y da cho.',
    'Bam sat tom tat va su kien chinh cua chuong nay.',
    'Viet cuc ky chi tiet: hanh dong, tam ly, doi thoai, mieu ta canh vat.',
    'Muc tieu: 5000-7000 tu.',
    'KHONG tu y them su kien ngoai dan y.',
    'Ton trong objective_refs, anchor_refs, state_delta va arc_guard_note neu duoc cung cap; khong duoc viet vuot muc dai cuc cho phep.',
    'current_status/Character Live Canon uu tien hon personality: personality la nen, current_status la rang buoc dang tac dong ngay trong chuong nay.',
    'Neu co [ANCHOR BAT BUOC CHO CHUONG NAY] thi chapter nay PHAI dat dung cac yeu cau do. Neu co [ANCHOR CHUA DEN HAN] thi khong duoc payoff som cac anchor do.',
    'KHONG duoc viet lai thanh canh chinh nhung gi da xay ra o cac chuong truoc; chi duoc nhac lai rat ngan neu can.',
    'Moi canh phai la he qua tiep noi tu chuong truoc va day tinh hinh sang trang thai moi.',
    'Chi tra ve noi dung chuong, KHONG them tieu de hay ghi chu.',
  ].join('\n'),
  [TASK_TYPES.GENERATE_MACRO_MILESTONES]: withPlanningAndCanonPrefix([
    'Hoach dinh DUNG so luong cot moc dai cuc duoc yeu cau cho dung PHAM VI LAP KE HOACH duoc cung cap; moi cot moc la mot diem ngoat LON cua hanh trinh.',
    'Neu dau vao co [SO LUONG COT MOC CAN TAO] thi mang milestones PHAI co dung bang do phan tu; khong duoc tu y roi ve mot con so mac dinh.',
    'Phai phan biet ro GIUA tong do dai du kien cua toan truyen va pham vi chapter dang duoc yeu cau lap dai cuc.',
    'Neu pham vi lap ke hoach khong bat dau tu Chuong 1 thi KHONG duoc tu y keo cot moc ve Chuong 1 va KHONG duoc coi pham vi do la toan bo truyen.',
    'Can phan bo hop ly trong pham vi duoc giao, co leo thang, khung hoang, dao chieu va tra gia ro rang.',
    'Neu tac gia co yeu cau rieng, uu tien toi da theo yeu cau do.',
    'Moi cot moc bat buoc phai tra ve them mot contract co cau truc de he thong dung cho planner va validator, khong chi mo ta bang van tu do.',
    'Neu dau vao co [YEU CAU BAT BUOC THEO CHUONG], cot moc chua chapter do PHAI dua cac yeu cau nay vao chapter_anchors trong contract; khong duoc chi nhac trong description.',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "milestones": [',
    '    {',
    '      "order": 1,',
      '      "title": "Ten cot moc",',
      '      "description": "Mo ta 2-3 cau",',
      '      "chapter_from": 1,',
      '      "chapter_to": 80,',
      '      "emotional_peak": "Cam xuc can dat",',
      '      "contract": {',
      '        "narrative_summary": "Noi dung cot loi cua cot moc",',
      '        "objectives": [',
      '          { "id": "OBJ1", "text": "Muc tieu cot loi", "focus_characters": ["Nhan vat A"] }',
      '        ],',
      '        "target_states": [',
      '          { "character": "Nhan vat A", "state": "Trang thai dich toi da duoc phep" }',
      '        ],',
      '        "focused_characters": ["Nhan vat A", "Nhan vat B"],',
      '        "forbidden_outcomes": ["Ket qua khong duoc xay ra trong cot moc nay"],',
      '        "max_relationship_stage": 1,',
      '        "chapter_anchors": [',
      '          { "id": "ANCHOR1", "target_chapter": 25, "strictness": "hard", "requirement_text": "Dieu bat buoc phai xay ra", "objective_refs": ["OBJ1"], "focus_characters": ["Nhan vat A"], "success_signals": ["Tin hieu thanh cong"], "forbid_before": true, "notes": "" }',
      '        ]',
      '      }',
      '    }',
    '  ]',
    '}',
    'Chi tra ve JSON.',
  ].join('\n')),
  [TASK_TYPES.ANALYZE_MACRO_CONTRACT]: withPlanningAndCanonPrefix([
    'Phan tich DUNG 1 cot moc dai cuc va chuyen no thanh contract co cau truc de planner/validator co the dung truc tiep.',
    'Day la buoc chuan hoa y do tac gia, khong phai viet lai cot moc cho dep hon.',
    'Phai bam sat noi dung cot moc duoc cung cap; khong tu y day nhanh tinh tiet, khong tu y them payoff, khong tu y nang muc quan he/plot len cao hon neu dau vao chua noi.',
    'Neu dau vao mo ho, hay dat objective va target_state o muc BAO THU, uu tien buildup/an toan hon la overshoot.',
    'Neu co phan "muc tieu", "ket qua", "tinh trang", "trang thai" trong text dau vao, phai uu tien doc dung cac phan do.',
    'Neu dau vao co chapter_anchors hoac yeu cau bat buoc theo chapter, phai giu lai va chuan hoa thanh chapter_anchors co cau truc; khong duoc lam mat.',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "contract": {',
    '    "narrative_summary": "Noi dung cot loi cua cot moc",',
    '    "objectives": [',
    '      { "id": "OBJ1", "text": "Muc tieu cot loi", "focus_characters": ["Nhan vat A"] }',
    '    ],',
    '    "target_states": [',
    '      { "character": "Nhan vat A", "state": "Trang thai dich toi da duoc phep" }',
    '    ],',
    '    "focused_characters": ["Nhan vat A", "Nhan vat B"],',
    '    "forbidden_outcomes": ["Ket qua khong duoc xay ra trong cot moc nay"],',
    '    "max_relationship_stage": 1,',
    '    "chapter_anchors": [',
    '      { "id": "ANCHOR1", "target_chapter": 25, "strictness": "hard", "requirement_text": "Dieu bat buoc phai xay ra", "objective_refs": ["OBJ1"], "focus_characters": ["Nhan vat A"], "success_signals": ["Tin hieu thanh cong"], "forbid_before": true, "notes": "" }',
    '    ]',
    '  },',
    '  "warnings": ["Canh bao neu dau vao qua mo ho, neu khong thi mang rong"]',
    '}',
    'Chi tra ve JSON.',
  ].join('\n')),
  [TASK_TYPES.AUDIT_ARC_ALIGNMENT]: withPlanningAndCanonPrefix([
    'Kiem tra do lech giua nhung chuong gan day va dai cuc/arc hien tai.',
    'Chi ra do lech cu the, khong noi chung chung.',
    'Tra ve CHINH XAC JSON format sau:',
    '{',
    '  "aligned": true,',
    '  "drift_score": 0,',
    '  "issues": ["Van de 1"],',
    '  "suggestions": ["De xuat 1"],',
    '  "current_position": "Tom ta vi tri hien tai cua truyen trong 1 cau"',
    '}',
    'Chi tra ve JSON.',
  ].join('\n')),
};
