-- OBSOLETE: do not use this file for the current StoryForge VIP deploy.
--
-- The split admin now uses the canonical access seed:
--   docs/supabase-access-control/002_access_control_seed.sql
--
-- This file is kept only so older deployment notes do not point to a missing
-- path. It intentionally contains no seed data.
