-- OBSOLETE: do not use this file for the current StoryForge VIP deploy.
--
-- The split admin now uses the canonical access schema:
--   docs/supabase-access-control/001_access_control_schema.sql
--
-- This file is kept only so older deployment notes do not point to a missing
-- path. It intentionally contains no schema.
