import { TASK_TYPES } from './router';

export const GLOBAL_PROMPT_META = {
  projectWizard: {
    title: 'Khởi tạo dự án bằng AI',
    summary: 'Dùng khi bạn đưa ý tưởng ban đầu để AI dựng blueprint truyện, nhân vật, thế giới và outline khởi đầu.',
    purpose: 'Prompt này điều khiển chất lượng của bước tạo dự án mới. Nó quyết định AI sẽ hiểu đề bài, dựng khung truyện và trả về JSON chặt chẽ đến mức nào.',
    whenToEdit: 'Sửa khi bạn muốn AI tạo truyện theo phong cách khác, chặt hơn về cấu trúc, ít sáo hơn, hoặc ép AI sinh blueprint sâu hơn ngay từ đầu.',
    commonInputs: 'Thể loại, tone, góc nhìn, cách xưng hô, độ dài dự kiến, synopsis, ý tưởng cốt lõi và gợi ý template.',
    expectedOutput: 'Một blueprint dự án hoàn chỉnh gồm premise, world profile, nhân vật, địa điểm, thuật ngữ, chương khởi đầu và plot thread.',
    impactArea: 'Ảnh hưởng đến mọi lần dùng AI Wizard để tạo truyện mới trên toàn app.',
  },
  outlineGeneration: {
    title: 'Tạo outline khởi đầu',
    summary: 'Dùng khi AI cần tạo dàn ý chương ban đầu hoặc bổ sung outline trong Outline Board.',
    purpose: 'Prompt này giúp AI chia chương, xác định purpose và summary của từng chương, đồng thời rút ra các tuyến truyện lớn từ outline tổng.',
    whenToEdit: 'Sửa khi bạn muốn outline chi tiết hơn, có nhịp rõ hơn, ít lặp ý, hoặc ép AI chia hồi/chương theo kiểu riêng của bạn.',
    commonInputs: 'Thông tin project, mô tả truyện, danh sách nhân vật, địa điểm, outline hiện có và yêu cầu outline mới.',
    expectedOutput: 'JSON chứa danh sách chương có title, purpose, summary, act và các plot thread rút ra từ outline.',
    impactArea: 'Ảnh hưởng đến luồng tạo outline khởi đầu và các lần AI bổ sung outline trong dự án.',
  },
  threadSuggestion: {
    title: 'Gợi ý tuyến truyện',
    summary: 'Dùng khi AI cần đề xuất thêm plot thread mới dựa trên synopsis, nhân vật và các chương hiện có.',
    purpose: 'Prompt này giúp AI đọc khoảng trống của câu chuyện và đề xuất thêm tuyến truyện đủ lớn để bổ sung chiều sâu, thay vì tạo chi tiết vụn vặt.',
    whenToEdit: 'Sửa khi bạn muốn AI ưu tiên tuyến chính, subplot, tuyến bí ẩn, tuyến tình cảm, hoặc yêu cầu thread phải mang tính bước ngoặt mạnh hơn.',
    commonInputs: 'Tên truyện, thể loại, synopsis, danh sách nhân vật, outline chương hiện tại và các tuyến truyện đã tồn tại.',
    expectedOutput: 'JSON chứa 2-3 plot thread mới, không lặp với tuyến cũ và có mô tả ngắn rõ mục đích.',
    impactArea: 'Ảnh hưởng đến các thao tác AI gợi ý plot thread trong quá trình lập kế hoạch truyện.',
  },
};

export const PROJECT_PROMPT_GROUPS = [
  {
    key: 'writing',
    title: 'Viết truyện',
    summary: 'Nhóm prompt trực tiếp điều khiển AI khi sinh nội dung truyện mới hoặc viết tiếp.',
    items: [
      {
        key: TASK_TYPES.FREE_PROMPT,
        label: 'Lệnh tự do trong truyện',
        type: 'text',
        purpose: 'Dùng khi bạn gửi một yêu cầu tự do cho AI trong ngữ cảnh dự án truyện, đặc biệt là các yêu cầu viết mới không khớp hoàn toàn với nút chức năng cố định.',
        whenToEdit: 'Sửa khi bạn muốn AI viết tự do nhưng vẫn bám thế giới truyện, viết dài hơn, bám giọng văn hơn hoặc bớt lan man.',
        commonInputs: 'Yêu cầu viết của tác giả, canon hiện tại, nhân vật, scene text, chapter context.',
        expectedOutput: 'Một đoạn hoặc chương mới đúng ngữ cảnh truyện, đúng giọng văn và không phá continuity.',
      },
      {
        key: TASK_TYPES.CONTINUE,
        label: 'Viết tiếp',
        type: 'text',
        purpose: 'Dùng khi AI nối tiếp đúng vị trí đang viết dở, không được reset cảnh và không được nhảy thời gian vô lý.',
        whenToEdit: 'Sửa khi bạn muốn AI chậm hơn, dài hơn, chi tiết hơn, hoặc bám sát nhịp văn hiện tại của cảnh.',
        commonInputs: 'Đoạn cuối đang viết, bridge memory, trạng thái cảm xúc, canon, scene contract.',
        expectedOutput: 'Phần viết tiếp liền mạch với văn bản trước đó, đúng giọng và đúng tiến độ của câu chuyện.',
      },
      {
        key: TASK_TYPES.SCENE_DRAFT,
        label: 'Viết nháp cảnh',
        type: 'text',
        purpose: 'Dùng khi AI sinh bản nháp đầu tiên cho một cảnh cụ thể trong chapter hoặc outline hiện tại.',
        whenToEdit: 'Sửa khi bạn muốn cảnh có nhịp nhanh/chậm hơn, tăng thoại, tăng mô tả, hoặc ép cảnh bám contract chặt hơn.',
        commonInputs: 'Outline cảnh, scene contract, nhân vật tham gia, địa điểm, canon facts, chapter direction.',
        expectedOutput: 'Một bản nháp cảnh đủ dài, rõ hành động, rõ tâm lý và có thể dùng làm nền để chỉnh tiếp.',
      },
      {
        key: TASK_TYPES.ARC_CHAPTER_DRAFT,
        label: 'Viết chương theo arc',
        type: 'text',
        purpose: 'Dùng khi AI viết trọn một chương dựa trên dàn ý arc đã được chốt sẵn.',
        whenToEdit: 'Sửa khi bạn muốn chương bám outline chặt hơn, viết dài hơn, hạn chế tự phát sinh sự kiện mới hoặc đẩy mạnh không khí chương.',
        commonInputs: 'Arc outline, chapter summary cần viết, mục tiêu chương, macro arc, canon và chapter liền trước.',
        expectedOutput: 'Một chương hoàn chỉnh bám arc hiện tại, không lạc sang chương khác và không phá đại cục.',
      },
    ],
  },
  {
    key: 'refine',
    title: 'Tinh chỉnh câu chữ',
    summary: 'Nhóm prompt dùng để làm giàu, viết lại hoặc chỉnh văn phong trên văn bản đã có.',
    items: [
      {
        key: TASK_TYPES.EXPAND,
        label: 'Mở rộng đoạn',
        type: 'text',
        purpose: 'Dùng khi bạn đã có đoạn gốc và muốn AI kéo dài nó ra mà không thay đổi bản chất sự kiện.',
        whenToEdit: 'Sửa khi bạn muốn AI tăng mô tả giác quan, thêm nội tâm, thêm thoại hoặc giữ sát hơn với văn bản gốc.',
        commonInputs: 'Đoạn văn gốc, selected text, scene context, giọng văn hiện tại.',
        expectedOutput: 'Một phiên bản dài hơn của đoạn cũ, phong phú hơn nhưng không làm lệch ý chính.',
      },
      {
        key: TASK_TYPES.REWRITE,
        label: 'Viết lại đoạn',
        type: 'text',
        purpose: 'Dùng khi bạn muốn AI giữ nguyên nội dung nhưng nâng câu chữ, nhịp văn và cảm xúc.',
        whenToEdit: 'Sửa khi bạn muốn AI viết mềm hơn, sắc hơn, đỡ máy hơn hoặc giữ nguyên cấu trúc chặt hơn.',
        commonInputs: 'Đoạn văn gốc, selected text, văn phong truyện, định hướng chất lượng câu chữ.',
        expectedOutput: 'Một bản viết lại tự nhiên hơn, hay hơn nhưng vẫn trung thành với nội dung ban đầu.',
      },
      {
        key: TASK_TYPES.STYLE_WRITE,
        label: 'Viết theo văn phong',
        type: 'text',
        purpose: 'Dùng khi bạn muốn AI sinh nội dung mới nhưng bám theo một mẫu giọng văn đã có.',
        whenToEdit: 'Sửa khi bạn muốn AI nhấn mạnh nhịp điệu, mức độ hoa mỹ, độ lạnh/lì, độ cổ phong hoặc tính hiện đại của giọng văn.',
        commonInputs: 'Mẫu văn phong, yêu cầu nội dung mới, scene context và mục tiêu cảm xúc.',
        expectedOutput: 'Một đoạn mới mang giọng văn gần với mẫu tham chiếu nhưng vẫn đúng nội dung cần viết.',
      },
    ],
  },
  {
    key: 'planning',
    title: 'Lên ý tưởng và lập kế hoạch',
    summary: 'Nhóm prompt phục vụ brainstorm, outline và định hướng tiến độ dài hạn của truyện.',
    items: [
      {
        key: TASK_TYPES.BRAINSTORM,
        label: 'Động não ý tưởng',
        type: 'text',
        purpose: 'Dùng khi bạn cần AI đề xuất nhiều hướng phát triển khác nhau cho một tình huống hoặc nút thắt.',
        whenToEdit: 'Sửa khi bạn muốn ý tưởng táo bạo hơn, logic hơn, đen tối hơn hoặc thiên về cảm xúc hơn.',
        commonInputs: 'Tình huống hiện tại, mục tiêu câu chuyện, nhân vật liên quan, tuyến truyện đang mở.',
        expectedOutput: 'Một danh sách hướng đi có xung đột, hậu quả và độ hấp dẫn rõ ràng.',
      },
      {
        key: TASK_TYPES.OUTLINE,
        label: 'Lập dàn ý chương',
        type: 'text',
        purpose: 'Dùng khi AI cần tạo dàn ý cho chương hoặc phần tiếp theo trước khi bắt đầu viết.',
        whenToEdit: 'Sửa khi bạn muốn outline chi tiết hơn, kịch tính hơn, có hook/cliffhanger mạnh hơn hoặc bám tuyến truyện tốt hơn.',
        commonInputs: 'Yêu cầu chương mới, synopsis, canon hiện tại, trạng thái nhân vật và thread đang mở.',
        expectedOutput: 'Một dàn ý có các điểm sự kiện rõ ràng, chuyển biến cảm xúc và đường dây căng thẳng hợp lý.',
      },
      {
        key: TASK_TYPES.PLOT_SUGGEST,
        label: 'Gợi ý hướng plot',
        type: 'text',
        purpose: 'Dùng khi AI cần đề xuất vài khả năng phát triển tiếp theo của cốt truyện.',
        whenToEdit: 'Sửa khi bạn muốn plot táo bạo hơn, an toàn hơn, nhiều hệ quả hơn hoặc ít cliché hơn.',
        commonInputs: 'Tình trạng truyện hiện tại, nhân vật chính, xung đột đang mở, canon đang có.',
        expectedOutput: 'Một số hướng plot tiếp theo có tóm tắt, xung đột và thay đổi cụ thể.',
      },
      {
        key: TASK_TYPES.ARC_OUTLINE,
        label: 'Dàn ý cho arc',
        type: 'text',
        purpose: 'Dùng khi AI cần lập kế hoạch cho cả một đợt chương mới thay vì chỉ một chương đơn lẻ.',
        whenToEdit: 'Sửa khi bạn muốn arc leo thang mạnh hơn, chậm hơn, rõ tiến độ hơn hoặc hạn chế giải quyết sớm tuyến lớn.',
        commonInputs: 'Mục tiêu arc, chapter trước đó, tuyến truyện đang mở, pacing mong muốn.',
        expectedOutput: 'Một danh sách chương mới trong arc với title, summary, key events và pacing rõ ràng.',
      },
      {
        key: TASK_TYPES.GENERATE_MACRO_MILESTONES,
        label: 'Gợi ý cột mốc đại cục',
        type: 'text',
        purpose: 'Dùng khi AI cần hoạch định các cột mốc lớn cho toàn bộ truyện để giữ tiến độ dài hạn.',
        whenToEdit: 'Sửa khi bạn muốn đại cục đậm chất hành trình hơn, khốc liệt hơn, nhiều trả giá hơn hoặc chia nhịp dài ngắn khác đi.',
        commonInputs: 'Ý tưởng tổng, thể loại, độ dài dự kiến, đích đến tối thượng và tình trạng hiện tại của truyện.',
        expectedOutput: 'Một bộ cột mốc lớn có thứ tự, phạm vi chương và cảm xúc cần đạt.',
      },
      {
        key: TASK_TYPES.AUDIT_ARC_ALIGNMENT,
        label: 'Kiểm tra độ lệch arc',
        type: 'text',
        purpose: 'Dùng khi AI cần đánh giá xem những chương gần đây có đang đi chệch khỏi đại cục hoặc arc hiện tại không.',
        whenToEdit: 'Sửa khi bạn muốn AI soi kỹ hơn độ lệch, nói thẳng hơn về drift hoặc đưa ra gợi ý sửa cụ thể hơn.',
        commonInputs: 'Các chapter gần đây, macro milestones, arc hiện tại, mục tiêu truyện và trạng thái tiến độ.',
        expectedOutput: 'Một bản đánh giá độ lệch có issue, suggestion và mô tả vị trí hiện tại của truyện.',
      },
    ],
  },
  {
    key: 'canon-memory',
    title: 'Canon và ghi nhớ',
    summary: 'Nhóm prompt giúp AI tóm tắt, trích xuất, kiểm tra continuity và cập nhật bộ nhớ truyện.',
    items: [
      {
        key: TASK_TYPES.CHAPTER_SUMMARY,
        label: 'Tóm tắt chương',
        type: 'text',
        purpose: 'Dùng để nén một chương thành bản tóm tắt ngắn phục vụ memory và điều hướng chương sau.',
        whenToEdit: 'Sửa khi bạn muốn summary chi tiết hơn, cô đọng hơn, nhấn mạnh cảm xúc hơn hoặc tập trung vào hậu quả canon hơn.',
        commonInputs: 'Toàn bộ nội dung chương vừa viết xong.',
        expectedOutput: 'Một tóm tắt ngắn nhưng đủ giữ lại sự kiện, nhân vật xuất hiện và trạng thái kết chương.',
      },
      {
        key: TASK_TYPES.FEEDBACK_EXTRACT,
        label: 'Rút trích thông tin mới',
        type: 'text',
        purpose: 'Dùng khi AI cần lấy ra nhân vật, địa điểm, vật phẩm hoặc thuật ngữ mới từ chương vừa viết.',
        whenToEdit: 'Sửa khi bạn muốn AI thận trọng hơn, chỉ lấy thông tin thật mới hoặc mô tả rõ hơn các entity được trích xuất.',
        commonInputs: 'Đoạn/chương vừa viết, canon hiện tại và ngữ cảnh truyện.',
        expectedOutput: 'JSON chứa các entity mới đủ rõ để cập nhật vào codex.',
      },
      {
        key: TASK_TYPES.SUGGEST_UPDATES,
        label: 'Đề xuất cập nhật codex',
        type: 'text',
        purpose: 'Dùng khi AI phân tích chương để đề xuất thay đổi trạng thái nhân vật và canon mới sau chapter.',
        whenToEdit: 'Sửa khi bạn muốn AI bảo thủ hơn, ít đề xuất hơn, hoặc chỉ chấp nhận thay đổi khi có bằng chứng rất rõ.',
        commonInputs: 'Chương hiện tại, character status hiện có, canon facts và các thay đổi vừa xảy ra.',
        expectedOutput: 'JSON đề xuất cập nhật trạng thái nhân vật và canon fact mới có reasoning.',
      },
      {
        key: TASK_TYPES.CANON_EXTRACT_OPS,
        label: 'Trích xuất thao tác canon',
        type: 'text',
        purpose: 'Dùng khi AI cần biến nội dung chương thành các typed operations để cập nhật canon engine.',
        whenToEdit: 'Sửa khi bạn muốn AI nghiêm hơn về bằng chứng, ít suy diễn hơn hoặc tập trung mạnh vào hậu quả canon.',
        commonInputs: 'Toàn bộ chapter, danh sách scene, canon hiện tại, thread title, nhân vật, địa điểm, vật phẩm.',
        expectedOutput: 'JSON ops có thể đưa thẳng vào canon engine để cập nhật projection hiện tại.',
      },
      {
        key: TASK_TYPES.CONTINUITY_CHECK,
        label: 'Kiểm tra continuity',
        type: 'text',
        purpose: 'Dùng khi AI rà xem nội dung có mâu thuẫn với canon, timeline, quan hệ, item và world rules hay không.',
        whenToEdit: 'Sửa khi bạn muốn AI khó tính hơn, bắt vấn đề sâu hơn hoặc ngược lại bớt bắt lỗi vụn vặt.',
        commonInputs: 'Chương/cảnh cần kiểm tra, canon facts, trạng thái hiện tại của nhân vật, item, quan hệ và world rules.',
        expectedOutput: 'JSON issues phân loại rõ loại lỗi, mức độ và gợi ý sửa ngắn gọn.',
      },
      {
        key: TASK_TYPES.CHECK_CONFLICT,
        label: 'Kiểm tra mâu thuẫn canon',
        type: 'text',
        purpose: 'Dùng khi AI cần tìm các mâu thuẫn rõ ràng giữa văn bản và sự thật đã được thiết lập.',
        whenToEdit: 'Sửa khi bạn muốn AI tập trung hơn vào conflict nặng, ít báo lỗi lặt vặt hoặc diễn giải suggestion cụ thể hơn.',
        commonInputs: 'Nội dung chương/cảnh, canon facts, trạng thái nhân vật và thông tin thế giới.',
        expectedOutput: 'JSON conflict list thể hiện loại mâu thuẫn, severity và cách sửa.',
      },
      {
        key: TASK_TYPES.CANON_REPAIR,
        label: 'Sửa lỗi canon',
        type: 'text',
        purpose: 'Dùng khi AI cần viết lại tối thiểu để một chương pass qua validator continuity.',
        whenToEdit: 'Sửa khi bạn muốn AI bảo toàn văn bản gốc hơn, sửa mạnh tay hơn hoặc ưu tiên các loại lỗi nhất định.',
        commonInputs: 'Bản chapter hiện tại, danh sách lỗi continuity và phần canon liên quan.',
        expectedOutput: 'Một phiên bản chapter đã sửa, giữ tối đa nội dung gốc nhưng loại bỏ lỗi continuity chính.',
      },
    ],
  },
  {
    key: 'writing-dna',
    title: 'DNA viết truyện',
    summary: 'Nhóm prompt nền điều khiển luật viết, giọng văn và các ràng buộc đặc biệt của truyện.',
    items: [
      {
        key: 'constitution',
        label: 'Luật cốt lõi',
        type: 'list',
        purpose: 'Đây là tập luật nền mà AI phải tuân thủ trong toàn bộ quá trình viết truyện cho project này.',
        whenToEdit: 'Sửa khi bạn muốn khóa thêm nguyên tắc sáng tác, cách xử lý nhân vật, mức độ logic hoặc tinh thần cốt lõi của truyện.',
        commonInputs: 'Thể loại, phong cách tác giả, nguyên tắc sáng tác và những điều tuyệt đối không được phá.',
        expectedOutput: 'AI giữ được bộ khung nguyên tắc xuyên suốt khi viết, thay vì chỉ nghe từng lệnh ngắn hạn.',
      },
      {
        key: 'style_dna',
        label: 'DNA văn phong',
        type: 'list',
        purpose: 'Đây là bộ quy tắc về giọng văn, nhịp điệu, độ hoa mỹ, độ cổ phong hoặc hiện đại mà AI phải bám theo.',
        whenToEdit: 'Sửa khi bạn muốn đổi nhịp văn, tăng độ mềm/cứng, tăng chất cổ phong hoặc siết văn phong sát gu riêng hơn.',
        commonInputs: 'Mẫu giọng văn mong muốn, nhịp kể, từ vựng ưu tiên và sắc thái cảm xúc chủ đạo.',
        expectedOutput: 'AI viết ổn định hơn về giọng điệu và ít bị trôi sang văn phong máy hoặc generic.',
      },
      {
        key: 'anti_ai_blacklist',
        label: 'Từ và cụm cần tránh',
        type: 'list',
        purpose: 'Danh sách này chặn các từ, cụm hoặc kiểu diễn đạt sáo mà bạn không muốn AI lặp lại trong truyện.',
        whenToEdit: 'Sửa khi bạn thấy AI hay dùng một số cụm từ khó chịu, cliché, đạo đức hóa hoặc meta-commentary lặp đi lặp lại.',
        commonInputs: 'Các từ cấm, cụm sáo, cụm AI hay lặp hoặc những biểu đạt phá giọng truyện.',
        expectedOutput: 'Văn bản sạch hơn, bớt chất AI hơn và gần gu người viết hơn.',
      },
      {
        key: 'nsfw_system_prompt',
        label: 'Luật nền NSFW',
        type: 'text',
        purpose: 'Đây là system prompt gốc cho toàn bộ chế độ NSFW của project khi bật nội dung trưởng thành.',
        whenToEdit: 'Sửa khi bạn muốn thay hệ luật NSFW mặc định bằng một bộ nghiêm ngặt hoặc đặc thù hơn cho truyện này.',
        commonInputs: 'Ranh giới nội dung, mức độ trần trụi, cách xử lý bạo lực/nhục dục và nguyên tắc không né tránh.',
        expectedOutput: 'Khi NSFW được bật, AI đọc bộ luật nền đúng với định hướng người viết cho project này.',
      },
      {
        key: 'nsfw_rules',
        label: 'Luật bổ sung NSFW',
        type: 'text',
        purpose: 'Đây là lớp luật bổ sung đọc sau luật nền NSFW, dùng để tăng ràng buộc riêng mà không cần thay toàn bộ system prompt NSFW.',
        whenToEdit: 'Sửa khi bạn chỉ muốn bổ sung thêm yêu cầu đặc thù cho truyện này mà vẫn giữ luật nền NSFW mặc định.',
        commonInputs: 'Các yêu cầu thêm về consent, bí mật, nhịp cảnh, hậu quả xã hội hoặc loại chi tiết phải tránh/giữ.',
        expectedOutput: 'AI vẫn dùng khung NSFW hiện có nhưng được gia cố bởi các luật riêng của project.',
      },
      {
        key: 'nsfw_intimate_prompt',
        label: 'Tăng cường cảnh thân mật',
        type: 'text',
        purpose: 'Prompt này chỉ được dùng để tăng cường khi AI viết cảnh thân mật hoặc 18+, giúp giữ nhịp, buildup và continuity của cảnh.',
        whenToEdit: 'Sửa khi bạn muốn cảnh thân mật chậm hơn, chi tiết hơn, nhiều aftermath hơn hoặc giữ áp lực bí mật mạnh hơn.',
        commonInputs: 'Yêu cầu viết cảnh thân mật, context quan hệ, trạng thái đồng thuận, bí mật và dư âm cảm xúc.',
        expectedOutput: 'Một cảnh thân mật có nhịp đúng, continuity tốt và ít bị viết tắt hay làm sạch quá mức.',
      },
    ],
  },
];

